### ISSUE TITLE
WSL problems with fork/exec

### ISSUE THREAD

**Issue by lionskape** [evilmartians/lefthook#111]
While executing on WSL getting an issue:

`fork/exec /bin/sh: invalid argument`

config example:
```yaml
pre-commit:
  commands:
    eslint:
      tags: frontend lint
      run: yarn eslint

**Comment by Arkweid** [comment]
Haven't windows to test it. Could you detect the problem?

**Comment by lionskape** [comment]
Hello. I have found a related issue for the WSL:
https://github.com/Microsoft/WSL/issues/3652

Seems like the simplest way is to notify users, that lefthook requires WSL with windows 18305 or greater.

Also, I found a workaround - lefthook can be triggered via PowerShell (inside a git hook), something like "powershell.exe lefthook <...>", but there are some pitfalls:
* lefthook have to be accessible from PowerShell
* if it is triggered by nodejs - there is a problem with forwarding streams. In version 16XXX it will work only with mapping stderr and stdout to the file.

**Comment by Arkweid** [comment]
Well, in powershell a lot of probles with different encoding/special charaters etc.
I suggest to use close to linux terminal like `mingw terminal`

**Comment by lionskape** [comment]
Actually, the problem is not inside PowerShell. Problem is in the WSL (it the closest to the linux).
Powershell can be used as a workaround (because it is possible to run a command through PowerShell inside WSL).

**Comment by lionskape** [comment]
WSL - Windows Subsystem for Linux, it is a Linux core inside windows.
On 16XXX version it is the only ubuntu-based system available.

**Comment by DerekNonGeneric** [comment]
Yikes, I just hit this problem in WSL myself.

```
fork/exec /bin/sh: invalid argument
```

I was looking forward to using this lefthook, but this is actually a dealbreaker for me. :(

**Comment by lionskape** [comment]
@DerekNonGeneric do you have an option to update your windows to the latest version and check if it works?

Seems like the problem was solved in future WSL releases.

**Comment by DerekNonGeneric** [comment]
Unfortunately, I do not have that choice at the moment as I am running Windows Server 2019, which does not have an upgrade path to WSL 2. :(

**Comment by mrexox** [comment]
This issue seems to be stale. I'm closing it. Feel free to reopen or mention me if it still reproduces.
