### ISSUE TITLE
Is there a way to not run pre-commit on merge?

### ISSUE THREAD

**Issue by Evilweed** [evilmartians/lefthook#115]
Hello, is there a nice way to setup Lefthook in a way that makes it not run pre-commit hooks on merge commits?

**Comment by Arkweid** [comment]
It not possible with config, but you can use LEFTHOOK=0 env variable.

**Comment by Evilweed** [comment]
@Arkweid I would like to avoid asking devs to manually write commands with env variables :) Any chance this could be added as a feature?

**Comment by Arkweid** [comment]
Good feature, but my time very limited this days.
If you make a PR I will merge it :)
If anyone interested I can explain how to achieve that.

**Comment by Evilweed** [comment]
@Arkweid if You would write the explanation here, and it will be my level of coding, then I'll do that. Although, never coded in GO before.

**Comment by Arkweid** [comment]
@Evilweed In general it works very simple.
When you put in terminal `git commit` the Git will call a hook file inside `.git/hooks` directory.
[Here an example how it looks like](https://i.gyazo.com/20c238fed0e2761c17e841925f23817e.png)
The list of possible hooks [here](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/githooks.html).
Same for `git merge` it just will call a few scripts file. So we want this:
1. Check what the Git state is(rebase? merge?).
2. Check lefthook.yml config.
3. If option `skip_rebase: true` or `skip_merge: true` exists and Git state equal to one of that state - just finish lefthook execution.
You could add such `if` statement here:
https://github.com/Arkweid/lefthook/blob/master/cmd/run.go#L93-L96
