### ISSUE TITLE
Feature Request: add Python package

### ISSUE THREAD

**Issue by lucatrv** [evilmartians/lefthook#119]
First of all thank you very much for the nice tool, in my opinion `leftook` is the best git-hooks manager out there today. I develop mostly in Python, and would like to move to `leftook` from [`pre-commit`](https://pre-commit.com/), which after having used it for some time I'm starting to hate...

Since you already provide `npm` and `gem` packages, do you plan to add a `pip` package in future? I know that there is already a [`lefthook` Python installer](https://github.com/life4/lefthook), but that is just a convenience script to either install `leftook` with `go get`, `brew`, `npm`, or `gem` (if you do not have either one installed, it does not work). An official Python package would allow to directly install and upgrade `leftook` using `pip`.

**Comment by lucatrv** [comment]
Note: I would be happy to contribute if I can be of help.

**Comment by Arkweid** [comment]
Hi @lucatrv, feel free to wrap lefthook into Python package. A will add it to docs.

**Comment by lucatrv** [comment]
OK @Arkweid I could to it, I would just need some spare time...

@orsinium since you already reserved the [`lefthook` name on `pypi`](https://pypi.org/project/lefthook/), once the new package is ready would you transfer its ownership to me? I ask because [you already proposed this to @Arkweid](https://github.com/Arkweid/lefthook/issues/63#issue-478900567).

**Comment by orsinium** [comment]
I didn't squat it. I made an actual package that installs lefthook. The question is why I didn't get feedback on it and why it wasn't added into docs.

**Comment by lucatrv** [comment]
I didn't say that you squatted it. Don't take me wrong, but currently your package is a convenience script to install the official package. If you have only Python installed, you cannot install it. You need either `go`, `brew`, `npm`, or `gem`. Once you have them, you can simply install the official package from there. This request would be for a self contained `pip` package. If you are available to develop it please go ahead, I think it would be very beneficial to spread the use of `leftook` within the Python community.

**Comment by Arkweid** [comment]
My fault. I just forgot to add it into docs. Fixed! 
https://github.com/Arkweid/lefthook/blob/master/docs/other.md#pip-for-python

**Comment by orsinium** [comment]
Just contribute into https://github.com/life4/lefthook, I'll make the release :) Don't get me wrong, I can share release permissions to the lefthook core team because they have no reason compromise lefthook releases, but not to everyone. Even if I have no time for active development, I can invest a bit for review and releases.

@Arkweid would you like to take care of lefthook python port repository?

**Comment by Arkweid** [comment]
> would you like to take care of lefthook python port repository?
I prefer community support. It's hard to maintain a lot of wrappers.

**Comment by lucatrv** [comment]
@orsinium this would not be contributing to your project, but rewriting your package from scratch. Sorry but I will not do it.

**Comment by orsinium** [comment]
Why so? Native installation can come as a fallback if npm/go/brew aren't available on the system.

**Comment by orsinium** [comment]
The decision to re-use existing packaging solutions comes from much cheaper maintenance. No need to update the package to keep installation always actual and working.

**Comment by lucatrv** [comment]
I do not agree, but if you think that's the correct approach go ahead. As for myself, I will install `lefthook` on my system directly with `npm`.

**Comment by thoroc** [comment]
> > would you like to take care of lefthook python port repository?
> 
> I prefer community support. It's hard to maintain a lot of wrappers.

Yes but then you get what is happening to that repo: it is now archived, with the potential to be plainly deleted.

> I do not agree, but if you think that's the correct approach go ahead. As for myself, I will install lefthook on my system directly with npm.

Devs that are not invested in the node ecosystem will probably not very happy to 'pollute' their repo with additional config file not related to their programming language of choice.

**Comment by bard** [comment]
I found this thread after looking for a way to include`lefthook` in a `poetry` project. FWIW, I think @lucatrv's initial suggestion of installing `lefthook` without reliance on non-Python toolchains was the right one (and I say this as someone who does mostly Type/JavaScript).

**Comment by qbedard** [comment]
Resurrecting with a bump to see where folks are on it. The Python package should absolutely be built with the binary included without reliance on external toolchains (`npm`, `gem`, etc) and should fallback to building it for unsupported platforms. This is what the majority of Python packages that bundle binaries do.

Are other folks still interested in this?

**Comment by mrexox** [comment]
I'd be glad to release lefthook with `pip`, but I think I need some help with this. If you can share an example of a project that distributes a binary with `pip` I'll appreciate it.

There's also an abandoned project https://pypi.org/project/lefthook/. Not sure if it's possible to delete it or somehow replace it. @orsinium, WDYT about transition of this project in pip (if it's possible)?

**Comment by orsinium** [comment]
I bet the project still works, despite being archived. 

I suggested earlier transferring ownership to the core team:

https://github.com/evilmartians/lefthook/issues/119#issuecomment-603774655

Otherwise, you are free to pick another name.
