### ISSUE TITLE
Documentation to work with commitlint?

### ISSUE THREAD

**Issue by radiosilence** [evilmartians/lefthook#122]
Unfortunately the commitlint documentation only has these instructions:

```json
{
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  }
}
```

And it's unclear whether lefthook exposes whatever `HUSKY_GIT_PARAMS` are in such a way that it works with commitlint.

**Comment by Arkweid** [comment]
Hi @radiosilence
It is impossible to store documentation for every tool in the world. Check the full guide and if you have a questions feel free to ask.

Maybe that what a you looking for?
https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md#bash-script-example

**Comment by muuvmuuv** [comment]
I use it like this:

```yml

    lint-commit:
      run: npx commitlint --from HEAD~1 --to HEAD
```

**Comment by tillsanders** [comment]
@muuvmuuv Somehow, this doesn't work for me. I also read, that the `pre-commit` hook should not work for this usecase. Apparently, the `commit-msg` hook should be used instead. Though this won't work for me as well :/

**Comment by tillsanders** [comment]
@Arkweid I took a look at your example using the bash script. I'm trying to figure out, how this could be used with a tool like commitlint without using a separate script file. Is there a way to access the commit message in the run command? Maybe using an environment variable or an argument?

**Comment by Arkweid** [comment]
For simple `run` lefthook not pass arguments from git.
If you need just a commit message, so as a mentioned above you could use a various git commands like [git show](https://git-scm.com/docs/git-show)

**Comment by muuvmuuv** [comment]
Oh, sorry, noticed that my above does not work, but this one does:

```yaml
commit-msg:
  commands:
    lint-commit-msg:
      run: npx commitlint --edit
```

```
  --edit, -e             read last commit message from the specified file or fallbacks to ./.git/COMMIT_EDITMSG
```

**Comment by paambaati** [comment]
I have a similar use-case with `git-notify`, where I need to pass Git parameters to `post-merge`, `post-rewrite` and `post-checkout` hooks, with the params being dynamic — https://github.com/jevakallio/git-notify#installing-hooks-by-any-other-means

Has someone had success doing this?

**Comment by muuvmuuv** [comment]
@paambaati where is this related to Commitlint? Post a new issue for this please.

**Comment by PawFV** [comment]
> ```yaml
> commit-msg:
>   commands:
>     lint-commit-msg:
>       run: npx commitlint --edit
> ```

For me the above one was **linting previous commit message** instead of the **current one**.
After reading lefthooks for a while I solved doing the following.

run:
```sh
lefthook add -d commit-msg
# will create .lefthook/commit-msg dir
```

Inside `.lefthook/commit-msg` create a bash script called `commit_check` and add the following.
```bash
if ! npx commitlint --edit --verbose; then
    exit 1
fi
```
Then in `lefthook.yml` add the following
```yml
commit-msg:
  scripts:
    'commit_check':
      runner: bash
```

Ref: https://github.com/evilmartians/lefthook/blob/master/docs/full_guide.md#managing-scripts

**Comment by theogravity** [comment]
Here's the current link:

https://evilmartians.github.io/lefthook/examples/commitlint.html
