### ISSUE TITLE
pre-commit not stopping commit

### ISSUE THREAD

**Issue by Roko131** [evilmartians/lefthook#149]
Hi
Even though `lefthook run pre-commit` returns errors I'm still able to `git commit` somehow.

0. `gem install lefthook`
1. I git clone your demo repo
2. changed ruby from `2.6` to `2.7.1`
3. Messed up js file
4. Ran `lefthook run pre-commit` to double check it found an error, and it did
5. But when I ran the `commit` command - it is still allowed, not being stopped

What am I missing?
Why isn't the `lefthook` being ran after `git commit`?

`ububtu 20.04` 
`ruby 2.7.1`
`git version 2.25.1`
`which lefthook` => `/home/my_user/.rbenv/shims/lefthook`

![image](https://user-images.githubusercontent.com/3532929/91208431-dfe55e00-e712-11ea-804b-afccf96e1da8.png)

**Comment by Roko131** [comment]
Maybe because I had edited git global core.hooksPath ?
`git config --global core.hooksPath /path/to/my/centralized/hooks`

**Comment by Roko131** [comment]
Indeed removing the global config solved it,
`git config --global --unset core.hooksPath`

Apparently having global `hookspath` (with pre-commit file inside) takes precedence over local hooks and basically ignore them.
Maybe worth adding to trouble shoot? though it's more of a `git` issue than a `lefthook`

**Comment by DmitryTsepelev** [comment]
Hi @Roko131, I've added a note to the [Troubleshooting guide](https://github.com/evilmartians/lefthook/wiki/Troubleshooting), thank you for the investigation!
