### ISSUE TITLE
When built with golang 15 a `fork/exec` error occurs when *running* `lefthook`.

### ISSUE THREAD

**Issue by NobbZ** [evilmartians/lefthook#151]
When using `lefthook run pre-commit` each individual hook fails with a `fork/exec` error. Some example run can be seen below:

```plain
$ lefthook run pre-commit
Lefthook v0.7.2
RUNNING HOOKS GROUP: pre-commit

  EXECUTE > formatting
 fork/exec /nix/store/cdrmdq9ckrffzlajj3hq1mz62l4z1v8c-bash-interactive-4.4-p23/bin/sh: Setctty set but Ctty not valid in child

SUMMARY: (done in 0.01 seconds)
🥊  formatting
```

I have been pushed to cespare/reflex#77 which had a similar issue and fixed it in cespare/reflex@456b3718abbf1922cfbd498521c27851250f5496.

Perhaps you can take something from this commit. Even though it seems to be "just" swapping one library for another, of which I am not even sure if that library is used in `lefthook`.

I have this problem with 0.7.2 as well as `master`.

**Comment by btd1337** [comment]
No updates?

**Comment by NobbZ** [comment]
With the release of Go 1.16 all packages built with Go 1.14 have been marked as insecure (as the Go team declared 1.14 as unsupported and insecure now) in my distribution now and I can not run `lefthook` anymore.

Please fix this issue.
