### ISSUE TITLE
Speed up on Node

### ISSUE THREAD

**Issue by ai** [evilmartians/lefthook#16]
Now we have 3 binaries in npm and [script](https://github.com/Arkweid/lefthook/blob/master/.npm/bin/index.js) which run necessary binary depends on the current platform.

There are 2 big problems with current behavior:

1. npm package size is huge (26 MB)
2. Node.js startup time is not great.

Solution:

1. `postinstall` script download necessary binary (many npm packages use this approach, for instance `puppeter`).
2. npm runs binary directly without `index.js`

**Comment by ai** [comment]
On CI we will avoid even downloading binary

**Comment by fleischie** [comment]
Hello all, especially @HellSquirrel (as you assigned this task to you),

How do I ask politely if I can offer my help with this task?

<details><summary>I made a prototype of how to download the binary on postinstall</summary>
I made a crude mockup that downloads the appropriate binary for the current OS (or fail if the OS isn't supported), and afterwards run the `install` command with the downloaded binary. The postinstall script already had a check for CI in place, that can be used to skip the downloading in it's entirety.

I am unsure still how to handle errors on downloading the binary.
</details>

But I wanted to ask first, whether this task is still being developed on, and whether I should share my version with somebody.

**Comment by HellSquirrel** [comment]
Hi @fleischie ! Thank you for your question and interest in this feature. 
I planned to do this task later, but if you want to help us it would be great!
If you already have a working draft just open a new pull request and we will continue the discussion there.
> Also I don't know where to store the binaries, if not in the .npm directory?

**Comment by ai** [comment]
On network error we should try 3 times and print error message with 1 exit code if we still have network error.

Also we need environment variable to prevent downloading (for instance, if there too is not used on CI).

**Comment by ai** [comment]
Puppeteer puts binaries to `node_modules/puppeteer` dir. We can do the same and put them in `lefthook` dir.

**Comment by sHooKDT** [comment]
I have a couple of questions here:

1. This way we break the possibility to install the package without the network. There are projects where CI runs in isolated environment and uses e.g. yarn offline mirror to achieve non-network-bound build process. I think we should at least provide a way to manually download and store the needed binary in project directory.
2. What if someone develops in mixed environment, e.g. WSL + Windows? It's not that rare when you are running dev server under WSL, but make a commit under Windows. Can we provide a way to download both needed binaries?

Sorry for skepticism, but the current solution covers such cases with zero effort.

**Comment by ai** [comment]
1. Isolated environments can use non-npm Lefthook distribution.
2. We can add it by request (especially for this rate case).

You will be surprised how many npm packages download content during install. For instance, Puppeteer or node-sass.

**Comment by sHooKDT** [comment]
@ai 
Thanks for comments!
I'm not surprised, just considering it not a best practice. Looks like kind of "workaround distribution" to me.

**Comment by ai** [comment]
Yeap. Sad that Go binaries is so big. I think downloading will be the smallest problem.

**Comment by ai** [comment]
@yumauri I think the size itself is not a problem. The problem is useless MBs :).

**Comment by fleischie** [comment]
As I mentioned in #43 (specifically [this comment](https://github.com/Arkweid/lefthook/pull/43#issuecomment-552379739)) I don't think we can just put the binary path into the `bin.lefthook` field in the package.json. It will interpret this as a path to a js-script, that it runs with a node environment (i.e. `node <package.json#bin.lefthook>`), which complains about a missing script.

I am uncertain whether we can get around the `index.js`-wrapper around the binary.

I am still willing to investigate/test further, if that is requested. I would then just need some pointers/ideas/etc. :smile:

**Comment by aminya** [comment]
I addressed some of the concerns in #184

**Comment by mrexox** [comment]
With new `lefthook` npm package this issue is solved: we removed the script and added an optional dependency that fetches the subpackage based on arch and OS.

It is fixed since v1.0.2
