### ISSUE TITLE
lefthook install not working: permission denied

### ISSUE THREAD

**Issue by deathcoder** [evilmartians/lefthook#161]
Hi,
I'm new to lefthook, we added it on our project and its working on our macos machine but i'm on ubuntu and i get this error:

```bash
$ lefthook install -v
open lefthook.yml: permission denied
```

i also tried `lefthook install -a` and `lefthook install -f`, even `sudo lefthook install` without success

permission for lefthook.yml files are as following:
```bash
$ ls -lia lefthook.yml 
39372773 -rw-rw-r-- 1 deathcode deathcode 285 dic 24 15:33 lefthook.yml
```

current version installed with `snap`: 
```bash
$ lefthook version
0.6.4
```
haven't tried yet with latest version

**Comment by Dhruv-Garg79** [comment]
Any solution? facing same issue.

**Comment by Envek** [comment]
Did you install it also via snap?

**Comment by Dhruv-Garg79** [comment]
sorry for the late response. yes, I also used snap.

**Comment by Envek** [comment]
Hmm, most probably problem is in strict [confinement](https://snapcraft.io/docs/snap-confinement) defined at the time of release here: https://github.com/evilmartians/lefthook/blob/v0.6.4/.goreleaser.yml#L55

We need to either re-release it with classic confinement or declare bunch of [interfaces](https://snapcraft.io/docs/supported-interfaces) (to be figured out which though). @Arkweid any thoughts?

**Comment by Envek** [comment]
Created classic confinement request in Snapcraft: https://forum.snapcraft.io/t/request-for-classic-confinement-lefthook/24166

**Comment by Envek** [comment]
Classic confinement has been granted. Now you can install latest version of Lefthook with following command:
```sh
snap install --classic lefthook
```
