### ISSUE TITLE
Making lefthook work with git-notify (by accessing git params)

### ISSUE THREAD

**Issue by paambaati** [evilmartians/lefthook#163]
I'm trying to get `lefthook` to with `git-notify`, where I need to pass Git parameters to `post-merge`, `post-rewrite` and `post-checkout` hooks, with the params being dynamic — https://github.com/jevakallio/git-notify#installing-hooks-by-any-other-means

Has someone had success doing this?

I can see in https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md#git-hook-argument-shorthands-in-commands that a specific Git hook argument at position `i` can be accessed with `{i}`, but is there a way I can access all arguments?

**Comment by Envek** [comment]
Isn't `{0}` is all arguments as you need?
> `{0}` - shorthand for the single space-joint string of Git hook arguments

Also you always can use [scripts](https://github.com/evilmartians/lefthook/blob/master/docs/full_guide.md#managing-scripts) and they always get all arguments on input. See https://github.com/Envek/lefthook-crystalball-example/blob/1056c79e7b239b3146c443edbe4142d21aff6a74/.lefthook/post-checkout/01-bundle-checkinstall#L3-L8 for example. Also you can read our [Lefthook, Crystalball, and git magic for smooth development experience](https://evilmartians.com/chronicles/lefthook-crystalball-and-git-magic) blog post with more details explanation.

**Comment by paambaati** [comment]
@Envek That works; must've missed this part of the documentation. Sorry for the trouble!
