### ISSUE TITLE
No native version for Mac m1

### ISSUE THREAD

**Issue by DanMossa** [evilmartians/lefthook#166]
```
❯ brew install Arkweid/lefthook/lefthook
==> Tapping arkweid/lefthook
Cloning into '/opt/homebrew/Library/Taps/arkweid/homebrew-lefthook'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 150 (delta 7), reused 0 (delta 0), pack-reused 118
Receiving objects: 100% (150/150), 20.99 KiB | 511.00 KiB/s, done.
Resolving deltas: 100% (32/32), done.
Tapped 2 formulae (28 files, 50.3KB).
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
```

It would be nice to have a native ARM version

**Comment by Envek** [comment]
Hey!

Please try this binary: [lefthook-0.7.2-darwin-arm64.tar.gz](https://github.com/evilmartians/lefthook/files/6346405/lefthook-0.7.2-darwin-arm64.tar.gz)


Or build one yourself with the following command from repository root (it will be in `dist/lefthook_darwin_arm64` folder):
```sh
goreleaser build --skip-validate --rm-dist
```

It will take some time for us to figure out how to release it properly, stay tuned!

**Comment by Envek** [comment]
Now you can install ARM64 version from Homebrew (no bottles for M1 currently, so it will be compiled from source on your machine):
```sh
brew install evilmartians/lefthook/lefthook
```
Also you can grab binary from [releases](https://github.com/evilmartians/lefthook/releases/), also it is included in Ruby gem and NPM package.
