### ISSUE TITLE
Custom hooks path isn't supported

### ISSUE THREAD

**Issue by Envek** [evilmartians/lefthook#170]
From [githooks documentation](https://git-scm.com/docs/githooks):
> By default the hooks directory is `$GIT_DIR/hooks`, but that can be changed via the `core.hooksPath` configuration variable (see [git-config[1]](https://git-scm.com/docs/git-config)).

I'm not sure about use cases for this and most probably if someone moves hooks directory to another place, they don't need Lefthook at all (cause they just can commit raw hook scripts right into the repo).

But, I can see in our codebase that in various places git hooks directory detection is done very different, e.g.:
https://github.com/evilmartians/lefthook/blob/04f9b560add658c45f226c2d524d7040d4b405c2/cmd/add.go#L154
https://github.com/evilmartians/lefthook/blob/04f9b560add658c45f226c2d524d7040d4b405c2/cmd/uninstall.go#L72
so may be it is at least a good occasion to do some refactoring just to keep things tidy?

**Comment by stevelacy** [comment]
`git rev-parse --git-path hooks` is the method to get the current hooks path with or without the `core.hooksPath` set
