### ISSUE TITLE
C# / Visual Studio example

### ISSUE THREAD

**Issue by bbodenmiller** [evilmartians/lefthook#174]
Would be nice if there was a C# example using Visual Studio.

**Comment by joshtune** [comment]
following

**Comment by DmitryTsepelev** [comment]
Hi! Lefthook works with Git projects in any language, what do you mean by "C# example"?

**Comment by bbodenmiller** [comment]
With Node you can install lefthook as a dev dependency. C# doesn't have that concept - someone could clone the repo and work on the project without ever ensuring lefthook was run. One potential workaround is requiring lefthook as part of VS project pre-build step.

**Comment by mrexox** [comment]
Hey! I think there is no need for a particular example. It's just like in any other project (Go, Rust, C#, Java, etc.) – install lefthook somewhere on your system, setup `lefthook.yml` and run `lefthook install`. See the [TL;DR](https://github.com/evilmartians/lefthook#tldr) section in the docs :)

**Comment by bbodenmiller** [comment]
See comment above. This doesn't do anything to ensure all devs working on
project have lefthook installed.

**Comment by mrexox** [comment]
Do you think it is lefthook's responsibility? Currently you'll have lefthook installed only when using lefthook NPM package. And even then you can disable postinstall scripts and avoid running `lefthook install`. So, I'm trying to avoid forcing to use lefthook.

**Comment by bbodenmiller** [comment]
If there is ways to automate or ensure lefthook usage by language/tool it'd
be helpful to document them. Lefthook is less useful if only some devs on a
project use it.

**Comment by mrexox** [comment]
There is an option to use [`assert_lefthook_installed`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#assert_lefthook_installed) setting. But it will only work if you have previously run `lefthook install`. No other ways are yet implemented
