### ISSUE TITLE
May I fix a wiki about installation?

### ISSUE THREAD

**Issue by ulwlu** [evilmartians/lefthook#191]
hi thank you for great oss.

I want to fix below

```
brew install lefthook
```

to below

```
brew install evilmartians/lefthook/lefthook
```

I just want to know if there is any remarks.

**Comment by skryukov** [comment]
Hi, @ulwlu! `evilmartians/lefthook/lefthook` is an outdated tap. We use the official `homebrew-core` and upate it on every release: https://github.com/Homebrew/homebrew-core/pull/77335

Why do you want to update it? Does `brew install lefthook` work on your machine?

**Comment by ulwlu** [comment]
Oh I see. `brew install lefthook` actually doesn't work.

```                                                                                                                                                                       
❯ brew install lefthook
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "lefthook".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

❯ brew -v
Homebrew 3.1.3
```

I guess we need to write about tap in wiki.

```
brew tap evilmartians/lefthook
brew install lefthook
```

**Comment by ulwlu** [comment]
@skryukov 
sorry, I reinstalled brew and it works. I should have done this before submitting issue. thank you for your reply.
