### ISSUE TITLE
Different versions cross git worktree

### ISSUE THREAD

**Issue by ryuran** [evilmartians/lefthook#192]
Hello

I still encounter an issue with 0.7.5 in a worktree #180

Error message:
> This command must be executed within git repository.
> Change working directory or initialize new repository with 'git init'.

- main git directory : lefthook 0.7.4
- git worktree directory : lefthook 0.7.5

It seems to use the lefthook version from the original git directory instead of the curren one.

**Comment by Envek** [comment]
How do you have installed lefthook? Most probably from Ruby gem or NPM? This is probably not Lefthook issue, I believe.

**Comment by ryuran** [comment]
With npm as a dev-dependency.

**Comment by Envek** [comment]
Ok, I found what's wrong. Here we search for lefthook binary relative to hooks directory path which is by default is relative to main worktree: https://github.com/evilmartians/lefthook/blob/49e3409f1c25b9058ebf2c19fc8b59f3af4169ce/cmd/templates/hook.tmpl#L11-L20

Most probably we need to search relative to current working directory or something like that.

**Comment by Envek** [comment]
Fix was just released in [0.7.6](https://www.npmjs.com/package/@arkweid/lefthook/v/0.7.6)
