### ISSUE TITLE
Feature request: Put the released DEBs and RPMs into repo

### ISSUE THREAD

**Issue by cerna** [evilmartians/lefthook#197]
This came as a reply to a discussion started in #189:

> From the one hand I think that we don't need excess files in GitHub releases

If excessive number of artifacts in a GitHub release is a problem, I think it would be worth to store them in system specific repository/channel.

(I am looking at it that for me to integrate Lefthook into the project, I had to distribute the `.deb` packages in my own channel - for downloading them from Github release is a bigger problem than setting a repository in `apt` and calling `sudo apt install lefthook`. If there was an official Debian (Fedora etc) repository for Lefthook, that would be splendid.)

This should not be adding (too much) work as these packages are build already for each release.

**Comment by aminya** [comment]
If the concern is about a suitable user-facing download page, then LeftHook should have a proper landing page. GitHub releases are not suitable for this purpose, and it doesn't cover everyone as many of the people want to use Lefthook through npm, bundle, etc.

**Comment by cerna** [comment]
While it is true that generally if you want to host your own repository for packages, you need to generate the metadata (index) your self, there are public services which offer open source programs: [Cloudsmith](https://cloudsmith.com/product/pricing/) and [Packagecloud](https://packagecloud.io/pricing) or [GemFury](https://gemfury.com) (I have no experience with GemFury). These offer a web interface (and CLI) where you just upload the packages, and it will generate the index metadata itself.

You can - of course - host these on your own with tools like [Aptly](https://www.aptly.info/) and other ([JFrog Artifactory](https://jfrog.com) etc). Hosting your own solution is a pain, but then you have total control and are shielded from the whims of provider companies.

**Comment by Envek** [comment]
> If the concern is about a suitable user-facing download page

No, concern is about getting updates for system-wide install of Lefthook.

For now. only really working distro-agnostic solution is [lefthook Homebrew formula](https://formulae.brew.sh/formula/lefthook#default) (Homebrew [supports Linux](https://docs.brew.sh/Homebrew-on-Linux) pretty well).

Another possible solution that works across distributions is Snap package, but Snapcraft moderators are ignoring [my request for classic confinement](https://forum.snapcraft.io/t/request-for-classic-confinement-lefthook/24166) and Lefthook isn't usable without it, unfortunately (see https://github.com/evilmartians/lefthook/issues/161)

**Comment by lskillen** [comment]
Hi folks - I work at Cloudsmith, and we're more than happy to help and support you. We do a huge amount in the community, and others have found Cloudsmith to be a fantastic distribution engine for them (e.g. RabbitMQ). You don't need to apply for OSS at Cloudsmith, just sign up, create an OSS repository, and away you go. If you've got any questions, you can ping me or the team on Intercom on the website (or here). :grin:

**Comment by Envek** [comment]
@lskillen, thanks for the recommendation! I've registered Lefthook as OSS project and manually uploaded latest debs and rpms into it.

@cerna, please set up repository by instructions from here: https://cloudsmith.io/~evilmartians/repos/lefthook/setup/#formats-deb and install lefthook by executing `sudo apt install lefthook --no-install-recommends` then (it tries to install some RPM tooling along the way and it is confusing).

I will keep this issue open until I set up CI for automatic updates publishing and add setup instructions to the docs along with [attribution, required by Cloudsmith](https://help.cloudsmith.io/docs/open-source-hosting-policy#attribution).

**Comment by mrexox** [comment]
Looks like the issue can be closed.
