### ISSUE TITLE
Can't install on windows via npm: EBADPLATFORM, notsup Actual Arch: ia32

### ISSUE THREAD

**Issue by gilbertohnrq** [evilmartians/lefthook#202]
I'm trying to install lefthook via npm on windows 10 and i'm getting this error:

PS C:\Users\Gilberto> npm i @arkweid/lefthook
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @arkweid/lefthook@0.7.5: wanted {"os":"darwin,linux,win32","arch":"x64,arm64,x32"} (current: {"os":"win32","arch":"ia32"})
npm ERR! notsup Valid OS:    darwin,linux,win32
npm ERR! notsup Valid Arch:  x64,arm64,x32
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gilberto\AppData\Roaming\npm-cache\_logs\2021-05-26T22_22_37_992Z-debug.log

**Comment by Envek** [comment]
Hm, most probably I screwed it up in https://github.com/evilmartians/lefthook/commit/7b44ebfb4fb8d77f0fe90924103de94bf24a0fd2 when I was choosing from [available values of `process.arch`](https://nodejs.org/api/process.html#process_process_arch).

Can you please show info about your OS and CPU from “About this computer” tab? Screenshot is fine.

Like, 32bit OS in 2021, is it real?

**Comment by gilbertohnrq** [comment]
![image](https://user-images.githubusercontent.com/29513598/119835078-e2a9f500-bed6-11eb-85b2-e69c0a3a0e10.png)

There it is.. I'm using a i5-10400, 16RAM, Windows 10 PRO 64bits

**Comment by Envek** [comment]
You're using 64bit OS, but why do you have 32bit Node.js then? How you have installed it? What is your development environment?

**Comment by gilbertohnrq** [comment]
> You're using 64bit OS, but why do you have 32bit Node.js then? How you have installed it? What is your development environment?

@Envek completely my bad, fixed it changing the version of nodejs. Sorry

**Comment by Envek** [comment]
But this is our NPM packaging bug anyway

**Comment by Envek** [comment]
Fix was just released in [0.7.6](https://www.npmjs.com/package/@arkweid/lefthook/v/0.7.6).

It would be awesome if you have some time to try to install lefthook on 32-bit Node.js and confirm that it is fixed. 

However, 0.7.6 will be the last version that includes 32bit binaries.
