### ISSUE TITLE
Provide a way to set the default path to lefthook

### ISSUE THREAD

**Issue by skryukov** [evilmartians/lefthook#204]
In `repare-commit-msg` hook I found next text:
```
#!/bin/sh

if [ "{$LEFTHOOK}" = "0" ]; then
	exit 0
fi

# lefthook_version: d41d8cd98f00b204e9800998ecf8427e

cmd="lefthook install"

if lefthook >/dev/null 2>&1
then
	exec $cmd
elif bundle exec lefthook >/dev/null 2>&1
then
	bundle exec $cmd
elif npx lefthook >/dev/null 2>&1
then
	npx $cmd
fi

cmd="lefthook run prepare-commit-msg $@"

if lefthook >/dev/null 2>&1
then
  exec $cmd
elif bundle exec lefthook >/dev/null 2>&1
then
  bundle exec $cmd
elif npx lefthook >/dev/null 2>&1
then
  npx $cmd
else
  echo "Can't find lefthook in PATH"
fi
```

I guess, it may be confusing, if folk uses this tool from Dart, but Lefthook try to use npx, ruby-stuff, etc. Can you provide API to set this commands implicitly by first install? I mean something like this:

```
lefthook install --install-command="pub global activate lefthook"
```

_Originally posted by @igorkamyshev in https://github.com/evilmartians/lefthook/issues/71#issuecomment-524967878_

**Comment by mrexox** [comment]
Hey! Is this issue still relevant? I've slightly changed the logic and moved most of ENV checking things into lefthook executable. Also install implicitly runs if needed in `lefthook run ...`.

**Comment by mrexox** [comment]
There is an option to extend the PATH with [`rc`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#rc) for lefthook. It sould solve this issue.
