### ISSUE TITLE
Why does it create a .husky folder?

### ISSUE THREAD

**Issue by icetbr** [evilmartians/lefthook#207]
Hi, does lefthook uses husky under the hood or it just uses the same folders?

Thanks

**Comment by skryukov** [comment]
Hi, @icetbr thanks for the issue!

Lefthook does not use husky and should not create a `.husky` folder. Could you provide more info about this? Which commands did you use?

**Comment by icetbr** [comment]
```
$ npx lefthook install
SYNCING lefthook.yml
⚠️  .husky directory does not exist, creating
SERVED HOOKS: pre-commit, prepare-commit-msg
```
