### ISSUE TITLE
The command output is suppressed while in progress

### ISSUE THREAD

**Issue by styx** [evilmartians/lefthook#208]
Version 0.7.3 has changed how the output is produced to the console. In the result i.e. when running `rspec` with progress bar you won't see it and only spinner from lefthook. And later 100% of progress bar. Also this is not comfortable when some tests are broken. You will know only in the end.

I believe this change introduced this regression https://github.com/evilmartians/lefthook/pull/130/files#diff-8146f8148ccbf6711d65f532f6ab9a7c8dfbdc3960c7ffc974f17d6d224dd349L260

**Comment by ShPakvel** [comment]
Agree. I suggest to return back ability to see logs from all invoked commands. At least it can be done via configuration or lets say env var. Though I feel like logs should be default behavior, and spinner set via configuration (or e.g. env var).

**Comment by Envek** [comment]
We have many controversal views on this behavior, so yes, it should be configurable.

For now, I can only recommend using `--fail-fast` option for rspec so it fails on the first broken test.

**Comment by iSuslov** [comment]
What if I have lefthook running in my CI. It outputs almost infinite `waiting` line during run. Look at the screenshot.
<img width="1021" alt="Screen Shot 2022-05-19 at 7 52 10 PM" src="https://user-images.githubusercontent.com/7628774/169422507-d17ce575-45b3-4ef5-869f-94fae61b4038.png">

**Is it really a desired behavior?**   

Anyway I want to see lefthook output in realtime. 
Why should I wait for my target to complete before I can see some debugging info? @Envek @Arkweid

**Comment by JoyceBabu** [comment]
My git client shows only the last 100 lines of output, and I can see only the spinner output.

**Comment by styx** [comment]
@mrexox it's unfortunate to say that, but behaviour is still different from what was in 0.7.2 version

0.7.2 https://youtu.be/rHzHpPlgIQc
1.2.5 with --no-tty https://youtu.be/pRHVMrwj_MA

**Comment by mrexox** [comment]
Hmm, I see. @styx, what do you think about `-f/--follow` option which would bring comment output to stdout like it did in 0.7.2? It is going to be a mess when used with [`parallel`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#parallel) option but I guess it would fit your needs.

I think we can switch to follow-mode implicitly for hooks without `parallel` option, but I need to make sure it doesn't break anything else.

**Comment by styx** [comment]
@mrexox sounds good to me
