### ISSUE TITLE
Uninstalling doesn't actually uninstall lefthook

### ISSUE THREAD

**Issue by Kachilero** [evilmartians/lefthook#216]
We had `lefthook` installed on a project, but do to some issues, we removed it. 

However, the `lefthook.yml` file keeps getting created and added to the repo. I don't know where the file that keeps adding it is and feel that `npm uninstall` should remove all traces of the package from the project.

At the very least there should be some documentation in the README about uninstalling.

**Comment by vaporyhumo** [comment]
I'm not sure, but maybe there is a leftover hook that is actually reinstalling lefthook. I think they use the `prepare-commit-message` hook for this, take a look at `.git/hooks/prepare-commit-message`.

**Comment by Kachilero** [comment]
@vaporyhumo Yes that might be the case. I have this in `.git/hooks/prepare-commit-message` 

```
#!/bin/sh

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

if [ -t 1 ] ; then
  exec < /dev/tty ; # <- enables interactive shell
fi

dir="$(git rev-parse --show-toplevel)"

call_lefthook()
{
  if lefthook -h >/dev/null 2>&1
  then
    eval lefthook $1
  elif test -f "$dir/node_modules/@arkweid/lefthook/bin/lefthook"
  then
    eval "$dir/node_modules/@arkweid/lefthook/bin/lefthook $1"
  elif bundle exec lefthook -h >/dev/null 2>&1
  then
    bundle exec lefthook $1
  elif npx lefthook -h >/dev/null 2>&1
  then
    npx lefthook $1
  elif yarn lefthook -h >/dev/null 2>&1
  then
    yarn lefthook $1
  else
    echo "Can't find lefthook in PATH"
  fi
}

# lefthook_version: a25d332481a8bb43fe436eb390e6e4c1

call_lefthook "install"

call_lefthook "run prepare-commit-msg $@"
```

Seems like this would be safe to remove, right?

**Comment by vaporyhumo** [comment]
Yes, it is. By default repos only have samples of what hooks should look like, If by any chance you want to restore them, just copy them from a new repo.

**Comment by mrexox** [comment]
`lefthook uninstall` uninstalls the hooks, not the `lefthook` executable. If you have it as a NPM dependency, you should uninstall it from the package.json. I'll add this to the docs
