### ISSUE TITLE
Add back Windows 32bit support

### ISSUE THREAD

**Issue by aminya** [evilmartians/lefthook#217]
I tend to challenge that market share chart attached to [this commit](https://github.com/evilmartians/lefthook/commit/70f6b51ebe0f618b946398ebe0db7c6fe9de69cc)

One of them is for performance tests of the computers, which are usually the newest, and the other is for gaming PCs, which are again the newest/fastest. 

If you look at the number of downloads, you will see that 7% of the windows users have downloaded the 32-bit version. This is the same as the number of Arm on MacOS and twice the Linux ARM users.

https://github.com/evilmartians/lefthook/releases/tag/v0.7.5

Windows 32 bit is used much more in places other than North America and Europe. The purpose of open source projects that want to use Lefthook is to be as accessible as possible to **all people around the world**, and providing Windows 32 bit support for Lefthook is just a matter of a few flags. So if possible please continue supporting it.

**Comment by Envek** [comment]
> If you look at the number of downloads, you will see that 7% of the people have downloaded the 32-bit version. 

Where did you get these numbers?

I couldn't find better statistics except those I referenced in the commit.

All CPUs produced in last maybe 10 years are capable of running 64 bit code. I don't know why people still continue to install 32-bit OSes on them (or install 32-bit runtimes on 64-bit OS like it was in https://github.com/evilmartians/lefthook/issues/202).

And older PCs have so limited amount of RAM so one hardly can do anything on them on modern development environment (Chrome consumes gigabytes of RAM by itself, all Atom-based software too).

While we can continue to build 32-bit binaries, I doubt that they're really used in the wild.

**Comment by aminya** [comment]
> Where did you get these numbers?

It shows on the download counter of the releases (you need [Refined GitHub](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf))

![image](https://user-images.githubusercontent.com/16418197/126171605-eea83dbb-2de4-469c-a7fa-377f29e5db36.png)

**Comment by mrexox** [comment]
Win32 executable is back!
