### ISSUE TITLE
add option for disabling the spinner

### ISSUE THREAD

**Issue by pwinckles** [evilmartians/lefthook#219]
It would be nice to have an option to disable the spinner similar to how colors can be disabled. The spinner produces output like the following in some environments:

```
[K⠋ waiting
[K⠙ waiting
[K⠹ waiting
[K⠸ waiting
[K⠼ waiting
[K⠴ waiting
[K⠦ waiting
[K⠧ waiting ....
```

**Comment by mrexox** [comment]
Hey! I've just added this option - [`no_tty`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#no_tty) and I am going to release it soon.
