### ISSUE TITLE
install does not look for the config in the root git path

### ISSUE THREAD

**Issue by spearmootz** [evilmartians/lefthook#227]
im sure this is not a very complicated fix but im not very well versed in GO.

when doing npx @arkweid/lefthook install seems to be looking for the lefthook.yml from the folder where the terminal is currently located folder rather than the root respository folder which is where the file is instantiated originally.

in reality my problem is another where because of this inconsistency of where the file is expected to be located, the post install script does not find it if the root folder is not the same as the package.json

**Comment by spearmootz** [comment]
just want to let anyone know that this is how i got around this.

i have a lefthook.yml it extends a lefthook-base.yml

and then in ./src i also have a lefthook that extends the base lefthook

**Comment by mrexox** [comment]
Hey! Looks like you use the stale package. Please, switch to lefthook NPM package. This issue should be fixed there.
