### ISSUE TITLE
Issue with hook template binary lookup / released binary on MacOS

### ISSUE THREAD

**Issue by PikachuEXE** [evilmartians/lefthook#232]
In https://github.com/evilmartians/lefthook/blob/master/cmd/templates/hook.tmpl#L18-L20

It tried to look for `./node_modules/@arkweid/lefthook`

But there are only multiple executable files inside folders for different platforms
![image](https://user-images.githubusercontent.com/1018543/134853305-b2d5d5a7-d03f-44ae-a360-3f1fb7fccd5c.png)
![image](https://user-images.githubusercontent.com/1018543/134853561-9179ca23-adc8-44c4-bc5c-5d4d6cd1cd4c.png)

I have no idea how to fix this

I am using SourceTree but it's able to detect base folder via 
https://github.com/evilmartians/lefthook/blob/master/cmd/templates/hook.tmpl#L11

But I am still unable to use due to this issue

**Comment by PikachuEXE** [comment]
Did some digging
[The few lines looking for `./node_modules/@arkweid/lefthook`](https://github.com/evilmartians/lefthook/blob/master/cmd/templates/hook.tmpl?rgh-link-date=2021-09-27T06%3A12%3A36Z#L18-L20) was introduced in
https://github.com/evilmartians/lefthook/commit/b742f15363325a99be49fba5bea6b6c9a572a054

But `.npm/bin/lefthook` was removed in https://github.com/evilmartians/lefthook/pull/184/files#diff-7125027dcfcca72f8a28cb0a3710322e1e4d1e52e2e346262406129862262b18

I still got no clue on how to fix this issue yet...

**Comment by aminya** [comment]
The improvements were never fully released. So, don't expect it to work.

**Comment by PikachuEXE** [comment]
I think this should be a duplicate to #99 then
