### ISSUE TITLE
`yarn` conditional may be unreachable in hook template.

### ISSUE THREAD

**Issue by andrewhampton** [evilmartians/lefthook#241]
The [hook template](https://github.com/evilmartians/lefthook/blob/master/cmd/templates/hook.tmpl#L24-L29) currently contains this logic:

```shell
  elif npx @arkweid/lefthook -h >/dev/null 2>&1
  then
    npx @arkweid/lefthook $@
  elif yarn lefthook -h >/dev/null 2>&1
  then
    yarn lefthook $@
```

However, I'm not sure it's possible for the yarn branch to ever execute. I think, if yarn is installed, npx will almost certainly be installed. If `npx` is available on the machine, it will automatically download and run `@arkweid/lefthook`.

I think these branches should be swapped. The yarn branch should only work if lefthook is already installed locally. If it's not already available locally, falling back to npx seems like a good option.

Alternatively, npx has a `--no-install` flag that will prevent it from automatically installing lefthook.

**Comment by dannobytes** [comment]
Got a PR up with the suggested change, hopefully this helps.

**Comment by mrexox** [comment]
Now in master, going to release it in v0.8.0
