### ISSUE TITLE
Problem With My Simple Project  With c#

### ISSUE THREAD

**Issue by DanielMouyal** [evilmartians/lefthook#243]
hello to all users I am new in visual studio I am want to do A small project  I create 2 form in the first form I Create A button that Open second form and Hide the first one. and in the second form, I create a windows media player that Plays a song so far all ok. I create an event that when I close the form on the X its will return to the first form and close the correct  form now my problem is when  the event close the  form that plays the song are and returns to the first form the music still works in the background  so its look like it's not close the form I will write here the code that you will see what I write 

this if the form number 1 

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Too_Windows
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {

           Form2 Form = new Form2();
           this.Hide();
           Form.ShowDialog();
           this.Close();

        }
    }
}

________________________________________________________________________________________________________

This  is form number 2 

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using WMPLib;

namespace Too_Windows
{
    public partial class Form2 : Form
    {
        public Form2()
        {
            InitializeComponent();

            axWindowsMediaPlayer1.URL = "Notis.mp4";

        }

        private void Form2_Load(object sender, EventArgs e)
        {

        }
        
        private void Form2_FormClosing(object sender, FormClosingEventArgs e)
        {

            Form1 Form = new Form1();
  
            Form.ShowDialog();

           
          
        }

    }
}

I try even this.Close();  and it make me a problem

**Comment by mrexox** [comment]
I guess your issues is not related to lefthook :thinking: 
This is a Go project and we used to do Go here :open_hands: 
Sorry, but I have to close this issue.
