### ISSUE TITLE
Improve call_lefthook

### ISSUE THREAD

**Issue by muuvmuuv** [evilmartians/lefthook#250]
When only using pnpm `call_lefthook` takes 20 seconds to call, because npx just takes so long.

Solution is adding `pnpm` before npx (and maybe move yarn before npx too) so these can call `node_modules` bin before using npx.

**Comment by muuvmuuv** [comment]
Oh, wait, I see there already is this `elif test -f "$dir/node_modules/@arkweid/lefthook/bin/lefthook"` but anyway this binary does not exist. See:

<img width="934" alt="Bildschirmfoto 2021-12-22 um 09 32 13" src="https://user-images.githubusercontent.com/11534760/147061480-7108833d-0e03-43b2-a1b9-49e6ca3b38c9.png">

So, this needs a fix too.

It would be way simple to add this, IMO: `$dir/node_modules/.bin/lefthook`. Because all package managers in node follow this spec.

**Comment by amertak** [comment]
I am experiencing the same issue, it takes too long to call it using npx.

**Comment by apathetic** [comment]
Do we know why the PR was closed?  I'd love to see a solve for pnpm, at the very least

**Comment by muuvmuuv** [comment]
I think the best way is to completely avoid dynamic installing lefthook like with npx and just stick with what could be locally installed and otherwise exit with a hint.

I don't know why it was closed but maybe because of bad grammar or typos or style idk.
