### ISSUE TITLE
LeftHook exits with 141 exit code on push

### ISSUE THREAD

**Issue by dekhanov** [evilmartians/lefthook#257]
```sh
❯ git push --set-upstream origin feature/PHW-134
Lefthook v0.7.7
RUNNING HOOKS GROUP: pre-push

lint (SKIP. NO FILES FOR INSPECTION)

  EXECUTE > deps

> repo@0.1.0 check:deps
> node tools/check-deps.js

Dependencies ok!


  EXECUTE > types

> repo@0.1.0 check:types
> tsc --noEmit



  EXECUTE > test

> repo@0.1.0 test
> npm run test:unit


> repo@0.1.0 test:unit
> jest

Test Suites: 27 passed, 27 total
Tests:       88 passed, 88 total
Snapshots:   21 passed, 21 total
Time:        35.361 s
Ran all test suites.

SUMMARY: (done in 134.41 seconds)
✔️  deps
✔️  types
✔️  test

❯ echo $?
141
```

But if I run lefthook like so: `❯ npx lefthook run pre-push` it exits with 0 as expected.

**Comment by dekhanov** [comment]
It looks like I've found the problem script.
The problem was with the tests script which runs Jest. 
I have updated Jest from 27.0.4 to 27.4.7 and the issue is gone. Have no idea what it was.

For those who want to reproduce:
macOS 12.0.1
git 2.34.0
node 16.10.0
npm 8.0.0
@arkweid/lefthook 0.7.7

**Comment by dekhanov** [comment]
Unfortunately, it started failing again. The problem is still with Jest. When I remove Jest script everything works fine.
```yml
pre-push:
  parallel: true
  commands:
    # test:
    #   run: jest
    lint:
      files: git diff --name-only HEAD @{push}
      glob: '*.{js,jsx,ts,tsx}'
      run: npx eslint {files}
    deps:
      run: npm run check:deps
    types:
      run: npm run check:types
```

**Comment by mrexox** [comment]
Hey! Have you tried the new version of lefthook? >1.0?

**Comment by dekhanov** [comment]
Hi @mrexox! Just updated Lefthook and the problem is still there, unfortunately.

**Comment by mrexox** [comment]
@dekhanov ,how is lefthook installed on your system? With `yarn` / `npm` / just as a binary?

Does it fail if you just run `lefthook run pre-push`?

lefthook itself returns either 0 or 1 exit code, so 141 - is a git returned code.

Found some info here: https://zditect.com/blog/56411338.html

Your pipeline taks about 2mins. Maybe there's something wrong with long-running pre-push hook :thinking:

**Comment by dekhanov** [comment]
@mrexox, hey!
I'm using npm. I also use [SCM Breeze](https://github.com/scmbreeze/scm_breeze) to run git commands.

I have updated Lefthook and Git to the latest versions. It is two errors now 🥲
The new one:

```sh
EXECUTE > lint

Oops! Something went wrong! :(

ESLint: 7.32.0

No files matching the pattern "{files}" were found.
Please check for typing mistakes in the pattern.
```

This error is unstable. Sometimes it works as expected: `lint: (SKIP. NO FILES FOR INSPECTION)`. 

The 141 code is still reproduced. I tried not to use git commands aliases and it worked sometimes, but eventually started finishing the process with 141 code again. Will take a look if it depends on the hook duration.

**Comment by mrexox** [comment]
> No files matching the pattern "{files}" were found.

This error was caused by `files` command. I will add more logging about it. Anyway, it shouldn't reproduce always. Than you for noticing.

I don't thing git aliases affect lefthook. Anyway, please, tell if you find the correlation between the error and hook duration :pray:

**Comment by dekhanov** [comment]
# An update after the moving to lefthook@v.1

It works fine! I had this 141 exit code error a few times, but recently everything was ok.
I have this 128 error sometimes, but it does not block the push. 
![An 128 error from task](https://user-images.githubusercontent.com/2033947/189305906-d67e4568-9dda-4ce4-bea9-884ed94d5be0.png)
