### ISSUE TITLE
Slow even when skipping

### ISSUE THREAD

**Issue by shanecav84** [evilmartians/lefthook#262]
- Node: 17.4.0
- Lefthook: 0.7.7

1. `mkdir test-lefthook`
1. `cd test-lefthook`
1. `git init .`
1. `yarn add -D @arkweid/lefthook`
1. `npx lefthook install`
1. ```yaml
    # lefthook.yml
    pre-commit:
      commands:
        slow:
          run: sleep 5
          skip: true
    ```
1. `git commit -m 'Setup'`
1. **Skipping**: `time git commit --amend --no-edit`
    - 1.42s user 0.44s system 84% cpu 2.196 total
1. **Disabled**: `time LEFTHOOK=0 git commit --amend --no-edit`
    - 0.01s user 0.02s system 20% cpu 0.161 total
1. `rm .git/hooks/prepare-commit-msg`
1. **Without _prepare-commit-msg_**: `time git commit --amend --no-edit`
    - 0.48s user 0.16s system 84% cpu 0.760 total


## Conclusions
- lefthook is much slower when skipping than when disabled
- The _prepare-commit-msg_ hook is auto-installed and adds a lot of overhead.

**Comment by sbleon** [comment]
It looks like it's the `npx @arkweid/lefthook -h` in `.git/hooks/prepare-commit-msg` that is really slowing things down.

- `time npx @arkweid/lefthook -h | tail -n 1`
  - `1.28s user 0.26s system 147% cpu 1.044 total`

If the `yarn` option came before the `npx` version, that would speed things up a lot:

- `time yarn exec lefthook -h | tail -n 1`
  - `0.13s user 0.06s system 48% cpu 0.394 total`

An `npm exec` option before `npx` option would also be a lot faster:

- `time npm exec lefthook -h`
  - `0.20s user 0.07s system 103% cpu 0.260 total`

**Comment by sbleon** [comment]
It looks like this is fixed in https://github.com/evilmartians/lefthook/commit/352531cfac5a3ec4b00146a970c43beb706cfa6a, at least for `yarn` users. That commit is in the latest release (v0.8.0).

Thanks, @dannobytes !
