### ISSUE TITLE
Unknown architecture: aarch64

### ISSUE THREAD

**Issue by GreatOmm** [evilmartians/lefthook#267]
Hi!
During an installation of an application package which does depend on Ruby Gems I got an error
> …/lefthook:12:in `&lt;main&gt;': Unknown architecture: aarch64 (RuntimeError)

I use lefthook-0.7.7 in a Parallels VM running Ubuntu on an ARM based Mac.
The solution was an additional line
> 	  when /aarch64/ then "arm64" # Linux ARM in Parallels
so that "aarch64" is also recognized as ARM architecture.

After this change my software did run. So please add also support for this ARM architecture. See [differences-between-arm64-and-aarch64](https://stackoverflow.com/questions/31851611/differences-between-arm64-and-aarch64) for details.

**Comment by mrexox** [comment]
Hey! With the latest lefthook (> 1.0) this should be fixed.
