### ISSUE TITLE
Full schema definition

### ISSUE THREAD

**Issue by jmgilman** [evilmartians/lefthook#270]
I've looked around in a few places, but I've not been able to find a full schema definition for the configuration file. The examples directory has a "full" example, however, it's actually missing several fields that I've found scrounging through the various bits of documentation. Is there a place I can find the full schema? I need it to do validation in our environments.

**Comment by mrexox** [comment]
Hey! With the new version 1.0.0 you can check the sources for actual schema. I will work on the docs to make it more convenient.

Here are the global fields: [config.go](https://github.com/evilmartians/lefthook/blob/master/internal/config/config.go)
Here is the hook fields: [hook.go](https://github.com/evilmartians/lefthook/blob/master/internal/config/hook.go)
Script and Command fields can be found here: [script.go](https://github.com/evilmartians/lefthook/blob/master/internal/config/script.go), [command.go](https://github.com/evilmartians/lefthook/blob/master/internal/config/command.go)

**Comment by mrexox** [comment]
I am closing this issue, as I guess full schema definition can be found in sources.
