### ISSUE TITLE
Could we get a release with the merge/rebase `skip` functionality?

### ISSUE THREAD

**Issue by p4checo** [evilmartians/lefthook#271]
Sorry for pushing, but I've been eagerly awaiting for a release containing the changes done in #173, which is apparently a part of the [0.8 milestone](https://github.com/evilmartians/lefthook/milestone/1), which in turn is pending on #204 which is open for more than a year now without any updates...

Would it be possible to release this as a part of 0.7 still? Thanks! 🙏🏼

**Comment by p4checo** [comment]
Thank you very much for [v0.8.0](https://github.com/evilmartians/lefthook/releases/tag/v0.8.0)! 🙇🏼

**Comment by Envek** [comment]
Thanks for the heads up and sorry for such a long break.

Please note that new version packages haven't been uploaded to all sources yet, release will be finished in a hour or two.

**Comment by Envek** [comment]
Oh, I completely forgot about Homebrew!

Thankfully they have automatic checks for new versions, so keep an eye on this pull request: https://github.com/Homebrew/homebrew-core/pull/103208
