### ISSUE TITLE
Create JSON schema

### ISSUE THREAD

**Issue by politician** [evilmartians/lefthook#288]
Create a JSON schema and add it to https://github.com/SchemaStore/schemastore so there will be support for validating / auto-completing configuration options within code editors.

For example, the [YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) VS Code extension supports it.

**Comment by hyperupcall** [comment]
I have made a PR for SchemaStore adding this: https://github.com/SchemaStore/schemastore/pull/3066

**Comment by mrexox** [comment]
Thank you so much @hyperupcall! I appreciate your work! :tada:

**Comment by hyperupcall** [comment]
That PR has been merged (accessible at https://json.schemastore.org/lefthook.json) - should this issue be closed now?

**Comment by politician** [comment]
Thank you !
