### ISSUE TITLE
`lefthook` package is missing `postinstall ` script

### ISSUE THREAD

**Issue by fantua** [evilmartians/lefthook#294]
Trying to use `lefthook` package according to this [doc](https://github.com/evilmartians/lefthook/blob/master/docs/node.md#install) via:
```console
yarn add -D lefthook
```

But pre-commit hooks doesn't work because there is no `postinstall` script:
https://github.com/evilmartians/lefthook/blob/abf62bc11d95b96c82ad95797b6eda56aaf6bc08/packaging/npm/lefthook/package.json#L1-L30

It exist only for `@evilmartians/lefthook` package:
https://github.com/evilmartians/lefthook/blob/abf62bc11d95b96c82ad95797b6eda56aaf6bc08/packaging/npm-bundled/package.json#L34

Is it expected?

**Comment by mrexox** [comment]
Hi! It is not expected because lefthook package has optional dependencies which resolve for each OS and arch.

**Comment by mrexox** [comment]
@fantua Did you run `yarn run lefthook install` after installation?

**Comment by fantua** [comment]
> @fantua Did you run yarn run lefthook install after installation?

No, I didn't. I expected this to be done automatically (using `postinstall` hook). Same as it’s done in `@evilmartians/lefthook`
