### ISSUE TITLE
support new config file format

### ISSUE THREAD

**Issue by fantua** [evilmartians/lefthook#319]
It will be really cool to add `.lefthook.yml` (with dot in the beginning) config file format support. Just to align with other libs:
- [lint-staged](https://github.com/okonet/lint-staged#configuration)
- [syncpack](https://github.com/JamieMason/syncpack#-configuration-file)
- [eslint](https://eslint.org/docs/latest/user-guide/configuring/configuration-files)

**Comment by mrexox** [comment]
Sounds cool! But I have concerns about how it would play with *overriding feature*. I mean, we support `lefthook.yml` as global config and `lefthook-local.yml` as local config which overrides values from global config. 

It would be confusing if we have both `.lefthook.yml` and `lefthook.yml`. Main questions is : how should we merge them? What config would be the "main"? Wouldn't it be confusing?

**Comment by fantua** [comment]
Good point! I think for this case we should support overriding feature. We just need to define priority order and use only one. Same as [eslint](https://eslint.org/docs/latest/user-guide/configuring/configuration-files) currently does:

> If there are multiple configuration files in the same directory, ESLint will only use one. The priority order is as follows:

For global it could be something like this:
1. `lefthook.yml` (potentially this format can be deprecated and removed in v2)
2. `.lefthook.yml`
3. `.lefthook.json` (maybe it's a good idea to add `json` format support)

For local:
1. `lefthook-local.yml`
2. `.lefthook.local.yml` (see [CRA](https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used) for `.local` reference)
3. `.lefthook.local.json`

**Comment by haysclark** [comment]
It seems like it would be best to treat any config file without `-local` as a core config.

You could get the core config file path via this regex [[regex101](https://regex101.com/r/GMOdjH/1)]:

```golang
^\.?lefthook\.(yml|yaml|json)
```

And any local configs via this regex [[regex101](https://regex101.com/r/2UK9j0/1)]:

```golang
^\.?lefthook-local\.(yml|yaml|json)
```

All of these scenarios would be supported:

Current
```
.
├── lefthook-local.yaml
└── lefthook.yaml
```

new dot configs
```
.
├── .lefthook-local.yaml
└── .lefthook.yaml
```

Even mixed.
```
.
├── lefthook-local.yaml
└── .lefthook.yaml
```

For config files conventions are pretty common these days.

**Comment by mrexox** [comment]
Wow, it makes sense! What do you think about default config file? I guess we could change it to be `.lefthook.yml` in v2 but still support `lefthook.yml` for existing projects.

Why do you think we should support JSON format? What is the potential use case?

Do you have a will to prepare a draft PR for this change?

**Comment by technicalpickles** [comment]
> Good point! I think for this case we shouldn’t support overriding feature. We just need to define priority order and use only one config file. 

Something I would add to this is to display a warning when multiple global config files are found, and say which is being used. This could be a pretty frustrating situation when you have both, trying to iterate on the file, and not see your changes taking an effect until you eventually discover that a different file is loading.
