### ISSUE TITLE
Lefthook uninstall should delete the hooks but not delete the config file

### ISSUE THREAD

**Issue by sheldonhull** [evilmartians/lefthook#325]
Lefthook uninstall is a destructive action, removing the actual config file.
Instead, I'd expect the uninstall to remove the hooks, but not delete the configuration.

Pre-commit uninstall does this, and it's nice as you can disable hooks while you run into issues to debug later, without accidentally deleting your hard built configuration 😀

## Update

I just found when reviewing the code there already is an option for keep configuration. Great!

I think i'll modify my proposal instead that the default behavior should be non-destructive for the config. Up for a PR to submit a change such as:

```go
	uninstallCmd.Flags().BoolVarP(
		&args.KeepConfiguration, "remove-config", "k", false,
		"remove the configuration file as well as the installed hooks",
	)
```

I think this would be a simple PR and be a lot more in alignment with other tooling in this area that I've used.

**Comment by mrexox** [comment]
Hey! Your proposal is fair enough, but I would like to have an option like `--force/-f` or `--remove-config/-f`, because `-f` flag is more common for the cases when you want to do something "dangerous", and removing a config file sounds like a dangerous operation. WDYT?

**Comment by sheldonhull** [comment]
@mrexox yes. I think that's the second part of the statement. I totally agree remove-config makes sense. Just the default behavior would be to remove hooks without uninstall. If that sounds good I'll try and send a PR your way. Cool?

**Comment by mrexox** [comment]
@sheldonhull, yep! :100:

**Comment by tspearconquest** [comment]
New user here, almost blew away the config in my team's repo because of this. Looking forward to this being submitted.

**Comment by sheldonhull** [comment]
Thank you for handling this. 🌮
