### ISSUE TITLE
Specific api documentation is missing or hard to find (trouble finding correct way to configure pnpm install hook post-checkout)

### ISSUE THREAD

**Issue by jeffvandyke** [evilmartians/lefthook#327]
I've spent some time trying to locate a complete explanation of what the lefthook.yaml file supports for options, what they do, and how they control hook execution, and all I can find is documentation by examples, which don't seem to provide the sort of documentation that would tell me in one obvious place that "If your command contains "{files}", then if there are no files that match the "glob" pattern, then the hook execution will be skipped." I'm not a huge fan of that sort of magic because commands like `pnpm install` only depend on `pnpm-lock.yaml`, but it's unclear how to create a hook that only executes if a specific set of files were changed.

If there exists documentation of this sort, it should be added to the README somewhere near the top under a "Docs" section. Feel free to comment or close, but having something like this would greatly improve the usability of this project.

**Comment by mrexox** [comment]
Fair enough. Since there are a lot of features (sometimes really magical), it is hard to find the best way to document them. But I will try to do so. Thank you for your issue. Please, feel free to point other unclear features that need to be well-documented.

**Comment by jeffvandyke** [comment]
One thing I'd like to see documented is a complete list of what other file placeholders besides {staged_files} there are, and how they affect when the hook runs. I think structuring it something like the [Docker Compose File specification](https://docs.docker.com/compose/compose-file/), it'd be nice to get clear documentation on all the available fields that can show up under the hook name in lefthook.yaml and how they affect hook running.
