### ISSUE TITLE
Extend a shared or remote config file

### ISSUE THREAD

**Issue by jcook-uptycs** [evilmartians/lefthook#340]
I see there is the `extend` option. All example use cases I have found show it with a local file. Is there a way to extend a remote or shared file? For example from a git repo.

I'm looking for a way to manage pre-commit hooks across all my repos. The extend option looks great, but seems to require the hooks to exist on the local system or in the repo. I'm looking to have one repo with all the hooks and use them across all repos. 

Thank you for your work on this. It looks like an awesome tool.

**Comment by mrexox** [comment]
Hey! Yes, there is an ongoing work in this PR: https://github.com/evilmartians/lefthook/pull/323. I am planning to finish it in 1-2 weeks.

With this feature we will take lefthook.yml (or another file, can be customized) from a git repo and merge its content to the local lefthook.yml. Stay tuned :)

**Comment by jcook-uptycs** [comment]
Awesome thank you!
