### ISSUE TITLE
What does the CI integration do? 

### ISSUE THREAD

**Issue by jcook-uptycs** [evilmartians/lefthook#342]
I see there is a ci integration. https://github.com/evilmartians/lefthook/blob/master/docs/full_guide.md#ci-integration

Just wondering what it does. 

Thank you for this great tool.

**Comment by mrexox** [comment]
It is useful for npm package. It skips running `lefthook install` (which is not needed in CI) in postinstall script.

P.S. Thank you for noticing. This is really not obvious from documentation :+1:

**Comment by mrexox** [comment]
I've updated the [docs](https://github.com/evilmartians/lefthook/blob/master/docs/usage.md#disable-lefthook-in-ci), so now it should be more obvious. Thank you for reporting!

**Comment by jcook-uptycs** [comment]
Thanks
