### ISSUE TITLE
Lefthook swallows STDERR for prepare-commit-msg

### ISSUE THREAD

**Issue by marques-work** [evilmartians/lefthook#344]
I have a `prepare-commit-msg` script that prints to STDERR and exits with a failure code when certain conditions are not met. However, lefthook refuses to display any output, and instead only propagates the exit code, but all output (STDERR or STDOUT) are silenced. I do not have any `skip_output` configured or `LEFTHOOK_QUIET` set.

How can I get errors from the script to print to the console?

**Comment by mrexox** [comment]
Hey! Yes, there is a "hack" - lefthook uses `prepare-commit-msg` hook to synchronize the git hooks with hooks in a config. The output is disabled by default just not to disturb users on every commit.

To enable output anyway I can add a special ENV handling, like `LEFTHOOK_VERBOSE=true` which will enable all output without suppressing. WDYT about it? Would it solve the problem?

**Comment by marques-work** [comment]
Hi @mrexox, yes that sounds like it might. Let me give it a try and I'll let you know if this works well. Thanks for the quick reply!

**Comment by marques-work** [comment]
@mrexox hmm, setting `LEFTHOOK_VERBOSE=true` doesn't seem to change anything.

In my `lefthook.yml`, I have the following config:

```yaml
prepare-commit-msg:
  scripts:
    "git-pair-commit-message.sh":
      runner: bash
```

And, in `.lefthook/prepare-commit-msg/git-pair-commit-message.sh`, I am echoing messages to both STDOUT and STDERR. Neither message is outputted to the console, though.

The way I am setting the environment variable is like so:

```bash
LEFTHOOK_VERBOSE=true git commit
```
Is this the correct way to do so?

**Comment by mrexox** [comment]
Hey! This feature is not implemented yet :) But I am on my way to release it with **1.1.4** today!

**Comment by marques-work** [comment]
Oh sorry, I misunderstood. But that's fast! Thanks!

**Comment by mrexox** [comment]
Please, tell if that works for you! Lefthook **v1.1.4** is now available with [`LEFTHOOK_VERBOSE`](https://github.com/evilmartians/lefthook/blob/master/docs/usage.md#lefthook_verbose) env support :slightly_smiling_face:

**Comment by marques-work** [comment]
yes, it works! thank you :)
