### ISSUE TITLE
Allow skipping pre-push on certain branches

### ISSUE THREAD

**Issue by Brcrwilliams** [evilmartians/lefthook#354]
### Summary

I work for GitLab. We have [a rather elaborate pre-push configuration](https://gitlab.com/gitlab-org/gitlab/-/blob/c879ed52672095fe965897280d1fc7ef5ac023d6/lefthook.yml) for lefthook, and we install lefthook automatically via the [GitLab Development Kit](https://gitlab.com/gitlab-org/gitlab-development-kit).
Something we have noticed as of late is that community contributors are confused by lefthook running (and often failing)
when they try to sync their forks with the upstream repository (meaning, they rebase master on upstream and then push to remote master on their fork). I would like to be able to add a configuration to `pre-push` hooks so that they can be skipped when on a certain branch (`master` in this case).

### Value

Since we install Lefthook automatically, contributors aren't very aware of what it is when they first encounter it. They may not realize that it is a git hook, or that it can be bypassed using `--no-verify`. Being able to skip lefthook on master would get rid of a lot of friction for these people.

### Behavior and configuration changes

I'd like to add a top-level configuration option onto `pre-push` that can be given a branch or ref, and will cause lefthook to skip _all_ commands when on that ref.

```yaml
pre-push:
  skip:
    - ref: master # When on master, skips both `a` and `b`
  commands:
    a:
      run: echo a
    b:
      run: echo b
```

**Comment by mrexox** [comment]
Hey @Brcrwilliams thank you for the issue! I hope to get to it as soon as possible and put it in a next release. 1-2 weeks at most. Don't hesitate to ping me :)

**Comment by mrexox** [comment]
Hey! Check out v1.2.2 version. The feature must be there :)

**Comment by Brcrwilliams** [comment]
This is great @mrexox 🙏 Thank you!
