### ISSUE TITLE
Most README example links are broken

### ISSUE THREAD

**Issue by smheidrich** [evilmartians/lefthook#380]
### Summary

The README contains a lot of links to examples under a file called `full_guide.md` which no longer exists (was removed in https://github.com/evilmartians/lefthook/commit/7c62002abc4d180c6c7d0abe704adc9473dd0dbd).

### Steps to reproduce

Look at the README's [Why Lefthook](https://github.com/evilmartians/lefthook#why-lefthook) section and click on any of the example links.

### Expected results

Arrive at a page showing the example in question.

### Actual results

Arrive at a GitHub 404 page.

### Possible Solution

Remove the links or replace them with ones that point to existing examples.

### Screenshots

No.

**Comment by mrexox** [comment]
Hey! Thank you for creating an issue! Gonna fix it soon!
