### ISSUE TITLE
Link broken in lefthook.yml after lefthook install

### ISSUE THREAD

**Issue by aaronkelton** [evilmartians/lefthook#400]
### Summary

The link in lefthook.yml file after running `lefthook install` is broken and needs to be updated

### Steps to reproduce

1. Install on a Mac using `brew install lefthook`
2. Run `lefthook install`
3. Open the generated `lefthook.yml` file and copy/paste the URL (https://github.com/evilmartians/lefthook/blob/master/docs/full_guide.md) into your browser
4. Observe the 404 page :(

### Expected results

I expect to see the usage guide

### Actual results

404 page

### Possible Solution

Change url to https://github.com/evilmartians/lefthook/blob/master/docs/usage.md

**Comment by mrexox** [comment]
Hey! Thank you for the issue. What is your `lefthook version` ?

**Comment by aaronkelton** [comment]
```
% lefthook version
1.2.6
```

**Comment by mrexox** [comment]
I must be already [fixed](https://github.com/evilmartians/lefthook/blob/master/internal/templates/config.tmpl#L4) since v1.2.3 :thinking:
