### ISSUE TITLE
`push_files` does not work on Windows

### ISSUE THREAD

**Issue by colin969** [evilmartians/lefthook#427]
### :wrench: Summary

Using `push_files` will fail on a Windows machine where Powershell is the default shell because `||` is not supported.
Push files generates file lists via `git diff --name-only HEAD @{push} || git diff --name-only HEAD master`

### Lefthook version

1.2.8 040297f4db3e30f94b403b87b1cc5cfe3054c321

### Steps to reproduce

Use `lefthook run pre-push` with a configuration like:

```yaml
pre-push:
  commands:
    test:
      run: echo {push_files}
```

### Expected results

Prints a list of files

### Actual results

`error replacing {push_files}: exit status 128`

### Possible Solution

Make sure that `cmd` is always used when executing this or all commands on Windows.

**Comment by mrexox** [comment]
Hey! Did you find a workaround?

**Comment by colin969** [comment]
Turns out I'm an idiot and forgot to enable verbose. It's an issue trying to use git lfs, haven't gotten around to digging for it though.

**Comment by mrexox** [comment]
Hm, yes, git lfs is not implicitly used, and it only breaks when it is required in a project. Please, come back when you investigate and find out a problem :pray:
