### ISSUE TITLE
problem synchronizing git hooks (Run 'lefthook install' manually) leads to .git/hooks/pre-commit: no such file or directory

### ISSUE THREAD

**Issue by srkimir** [evilmartians/lefthook#430]
### :wrench: Summary

Due to how git clone works, according to my knowledege, git hooks are not transferred when cloning.
lefthook not creating .git/hooks automatically?
**Error: open .git/hooks/pre-commit: no such file or directory**

### Lefthook version

1.3.0

### Steps to reproduce

Clone whatever repository, add lefthook as dependency (npm install) define whatever hook and try to run it.
You will get:
```
There was a problem with synchronizing git hooks.
Run 'lefthook install' manually.
```

After trying to run it manually (**which i suppose i shouldnt?**) i get following:
Error: open .git/hooks/pre-commit: no such file or directory

### Expected results

After cloning whatever repo, doing npm install and having lefthook.yml, shouldnt i be able to use it as-is? without any
further config? why **lefthook install** is needed?

### Actual results
Error: open .git/hooks/pre-commit: no such file or directory

### Possible Solution
Create .git/hooks folder out of the box after lefthook is installed, if .git/hooks folder is not there?

**Comment by mrexox** [comment]
Hey @srkimir! Could you please provide a link to a repo you cloned? `git --version` could help too. I'll try to reproduce this behavior.

**Comment by srkimir** [comment]
hey @mrexox first of all thank you very much for the comment

**git version 2.37.1 (Apple Git-137.1)**

i just created repositories, can you please clone it and check?
https://github.com/srkimir/lefthook-git-hooks-folder-bug

so if you do `npm install` i would expect lefthook to prepare everyhing, so you as a new developer in that repo shouldnt not do anything to setup hooks (that is the reason why im trying to run away from husky)

so if you do something like `npx lefthook run prettier` you will get
Lefthook v1.3.0
SYNCING
**⚠️  There was a problem with synchronizing git hooks.
Run 'lefthook install' manually.** 
and lefthook command will not work

Once again thank you for assisting on this

**Comment by mrexox** [comment]
Let me share my steps. Unfortunately I couldn't reproduce the issue:

```bash
[/tmp] $ git clone https://github.com/srkimir/lefthook-git-hooks-folder-bug.git
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 0), reused 7 (delta 0), pack-reused 0
[/tmp] $ cd lefthook-git-hooks-folder-bug/
[/tmp/lefthook-git-hooks-folder-bug] main $ npm install

added 3 packages, and audited 4 packages in 3s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[/tmp/lefthook-git-hooks-folder-bug] main $ cat lefthook.yml
pre-commit:
  parallel: true
  commands:
    prettier:
      glob: "*.js"
      run: npm run format {staged_files}
[/tmp/lefthook-git-hooks-folder-bug] main $ npx lefthook run pre-commit
Lefthook v1.3.0
RUNNING HOOK: pre-commit
prettier: (skip) no files for inspection

SUMMARY: (SKIP EMPTY)
[/tmp/lefthook-git-hooks-folder-bug] main $ s
[/tmp/lefthook-git-hooks-folder-bug] main $ ls
index.js  lefthook.yml  node_modules  package-lock.json  package.json  README.md
[/tmp/lefthook-git-hooks-folder-bug] main $ vim index.js
[/tmp/lefthook-git-hooks-folder-bug] main $ s
 M index.js
[/tmp/lefthook-git-hooks-folder-bug] main $ git add -A
[/tmp/lefthook-git-hooks-folder-bug] main $ npx lefthook run pre-commit
Lefthook v1.3.0
RUNNING HOOK: pre-commit

  EXECUTE > prettier

> lefthook-git-hooks-folder-bug@1.0.0 format
> npx prettier --write index.js "index.js"

index.js 46ms


SUMMARY: (done in 0.79 seconds)
✔️  prettier
```

Could you show some content of the folder after cloning? And there are also some commands that can help to get more context about the issue: 

```bash
git clone https://github.com/srkimir/lefthook-git-hooks-folder-bug.git
cd lefthook-git-hooks-folder-bug
ls -al .
ls -al .git/
npx lefthook install --verbose
npx lefthook run pre-commit --verbose
```

**Comment by mrexox** [comment]
Ok, I see the issue - hooks dir is missing. I don't know why, but this is weird. I'd like to suggest a few options:

1. Try `mkdir .git/hooks` and then `npx lefthook install` (a workaround, but not a general solution)
2. Try updating your `git` to the latest version and reproducing the bug again.
3. Try looking through your `git config -l` to see if there is a configuration for the hooks folder. `core.hooksPath` is the setting name.

I'll add a force creation of hooks folder to the nearest patch version. And this should also help. Going to release it with v1.3.1.

>  one should not use manually npx lefthook install. hould that be automatically executed after npm install?

Yes, it is automatically executed in postinstall script of an npm package. However it failed because there wasn't `.git/hooks`
