### ISSUE TITLE
Enable glob for git ref

### ISSUE THREAD

**Issue by iafelix** [evilmartians/lefthook#456]
### :zap: Summary

I would like to have `glob` behaviour for Git `branch` name like so:

```yaml
  skip:
    - ref: 'main/*'
```

Currently it only accepts hard coded like this:
```yaml
  skip:
    - ref: main
```

### Value

With that `skip` option in place, we can `skip` versioning branches such as:
```yaml
  - main/v1.2.9
  - main/3.8.1-apha
```

Otherwise we have to edit the config file every time we deploy a new tag, then raise a new PR, etc.

**Comment by mrexox** [comment]
Hey @iafelix! Check 1.3.7 version with globs support for `ref`s in `skip` option :rocket:
