### ISSUE TITLE
GitLab: LFS objects are missing

### ISSUE THREAD

**Issue by sevilyilmaz** [evilmartians/lefthook#472]
### :wrench: Summary

lefthook [runs](https://github.com/evilmartians/lefthook/blob/master/docs/usage.md#git-lfs-support) LFS hooks under the hood. I have git lfs installed but lefthook doesn't seem to run `pre-push` hook as my commits get rejected by the server with this error:

```
remote: GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".
```

### Lefthook version

`1.3.10 58f5e02b582907284d97faa4b2dce3197ce5664e`

### Steps to reproduce

1. Enable git lfs in a repo
2. Commit a change that has a large file in it
3. Push the commit

### Expected results

I expect `git lfs pre-push {push_files}` to run under the hood so I won't do it manually.

### Actual results

See the error message in the description field.

### Possible Solution

Run  git lfs' `pre-push` hook together with git's `pre-push` hook. e.g `git lfs pre-push {push_files}`

### Screenshots (if appropriate)

Not needed

**Comment by mrexox** [comment]
Thank you for the issue. I will take a look at it in 2-3 days.

Could you please show the output of lefthook with `LEFTHOOK_VERBOSE=true`? What command do you run? I guess it is `git push`, so could you please send the output of this command:

```bash
LEFTHOOK_VERBOSE=true git push
```

**Comment by sevilyilmaz** [comment]
It didn't give any extra information but here it is.

```
LEFTHOOK_VERBOSE=true git push origin lefthook-pre-hook-test -u
extends []
          
Lefthook v1.3.10
RUNNING HOOK: pre-push
Enumerating objects: 30, done.
Counting objects: 100% (30/30), done.
Delta compression using up to 8 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (18/18), 3.98 KiB | 1.99 MiB/s, done.
Total 18 (delta 6), reused 0 (delta 0), pack-reused 0
remote: GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".
To [REPO_URL_REDACTED]
 ! [remote rejected]   lefthook-pre-hook-test -> lefthook-pre-hook-test (pre-receive hook declined)
error: failed to push some refs to '[REPO_URL_REDACTED]'
```

**Comment by mrexox** [comment]
@sevilyilmaz, do you have `git-lfs` executable in your PATH? I don't see debug logs related to `git lfs` command, and this might happen when the executable is unavailable :thinking: What does this return on your system?

```bash
which git-lfs
```

**Comment by mrexox** [comment]
Ok, I still don't understand why there's a problem with LFS, so I'll ask you to provide a few more details:

1. Do you have `pre-push` hook in your `lefthook.yml`? If yes, could you send its configuration please? If not, please add some dummy hook like below and try `LEFTHOOK_VERBOSE=true git push`

```yml
pre-push:
  commands:
    lfs:
      run: echo 'Triggering LFS'
```

2. If (1) doesn't help, could you send the output of `lefthook run pre-push -v`?

**Comment by mrexox** [comment]
Ok, looks like lfs hook is being executed but without files argument or something else is wrong with it.

You can see the command in debug logs (1) marked as `[git-lfs]`. Can you run it manually before pushing and then pushing without lefthook - `LEFTHOOK=0 git push`. Does it work that way?

**Comment by sevilyilmaz** [comment]
When I ran `git lfs pre-push` the command just hang. It might be related to the error in the 2. log: `This should be run through Git's pre-push hook.`.

I ran the `push` command manually which uploaded large files;

```
git lfs push --all origin lefthook-pre-hook-test

Uploading LFS objects: 100% (3280/3280), 25 MB | 0 B/s, done. 
```

Then `git push` was possible.


```
LEFTHOOK=0 git push origin lefthook-pre-hook-test -u

Enumerating objects: 30, done.
Counting objects: 100% (30/30), done.
Delta compression using up to 8 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (18/18), 3.98 KiB | 1.99 MiB/s, done.
# ...
 * [new branch]        lefthook-pre-hook-test -> lefthook-pre-hook-test
branch 'lefthook-pre-hook-test' set up to track 'origin/lefthook-pre-hook-test'.
```

**Comment by sevilyilmaz** [comment]
I just change large files again and tried to push, and they worked. So, it might be related to not having an upstream as it is mentioned in this log.

```
[lefthook] cmd: [sh -c git diff --name-only HEAD @{push}]
[lefthook] err: exit status 128
[lefthook] out: fatal: no upstream configured for branch 'lefthook-pre-hook-test'
```

**Comment by mrexox** [comment]
Do you have a public repo on GitLab, so I could test this behavior to see what's wrong with LFS hooks? :thinking:

**Comment by sevilyilmaz** [comment]
It's a self-hosted Gitlab instance. If the comment above doesn't give you a hint I can try to reproduce it in a Gitlab repo.

**Comment by mrexox** [comment]
> It's a self-hosted Gitlab instance. If the comment above doesn't give you a hint I can try to reproduce it in a public Gitlab repo.

That would be nice! It will make debugging much faster. Thank you!

**Comment by sevilyilmaz** [comment]
I could not reproduce the issue in an public repo and since I cannot reproduce it in our internal repo I'll close this issue. If it happens again and I have more information I'll reopen it. 

Thank you for following up
