### ISSUE TITLE
Documentation request - `lefthook install`

### ISSUE THREAD

**Issue by istrasci** [evilmartians/lefthook#496]
### :zap: Summary

Add text/links to **Install** instructions concerning the `lefthook install` command for more visibility.

### Value

I realize it is not technically part of installation, but I feel that the `lefthook install` command is the first logical step to perform after installation.  However, this is not apparent (at least to me) from the current organization of the documentation, and can be particularly confusing for new users who do not know that this step is required.

### Behavior and configuration changes

It would be nice to see some text in the **[Install](https://github.com/evilmartians/lefthook#install)** section of the README indicating that running `lefthook install` after installation is a logical next step.  And/or something similar in the **[Installation guide](https://github.com/evilmartians/lefthook/blob/master/docs/install.md)**.

**Comment by istrasci** [comment]
> Isn't the first step to define a `lefthook.yml`?

Current docs say

> Run lefthook install to initialize a lefthook.yml config and/or synchronize .git/hooks/ with your configuration.

So the file is not strictly needed before running `lefthook install`.

**Comment by mrexox** [comment]
Hey! I've added a [TL;DR](https://github.com/evilmartians/lefthook#tldr) instructions and also updated the [Usage](https://github.com/evilmartians/lefthook/blob/master/docs/usage.md) page. Does it feel good?

**Comment by istrasci** [comment]
Yes, looks great!  Thanks!
