### ISSUE TITLE
Provide an Alpine Linux (aports) package

### ISSUE THREAD

**Issue by sanmai-NL** [evilmartians/lefthook#502]
### :zap: Summary

Provide an Alpine Linux (aports) package, so that developers and DevOps professionals can use Lefthook more easily from within a container. See #222 too.

### Value

Alpine Linux is heavily used in the Linux container space.

### Behavior and configuration changes

Follow https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package and submit the package to Alpine Linux. The role of maintainer needs to be fulfilled (but this shouldn't be much work once the package is first done).

**Comment by mrexox** [comment]
Thank you! This is a good idea. I will take a look.

**Comment by sanmai-NL** [comment]
The [Melange](https://github.com/chainguard-dev/melange) tool claims to make this easier than following the guide on the Alpine Linux wiki.
