### ISSUE TITLE
Supply directory path as template

### ISSUE THREAD

**Issue by sanmai-NL** [evilmartians/lefthook#503]
### Value

Some linters recursively scan directories rather than opening separate files. Some tools such as container engines need a full path of the current working directory to e.g., set up a bind mount.

### Behavior and configuration changes

Add `{dir_root}` and `{dirs}` templates. The former is the absolute path of the root directory, the latter contains the set of parent directories of all changed files.

**Comment by mrexox** [comment]
Hey! Your case is very specific I guess. For the specific cases there is a [`files`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#files) option where you can provide your command/script that will generate the desired files or dirs. Have you tried it?

**Comment by sanmai-NL** [comment]
That seems a fine solution. But the docs would better be improved to say that `{files}` doesn't necessarily mean files, but paths.
