### ISSUE TITLE
`pre-push` hooks are broken because lefthook does not forward STDIN

### ISSUE THREAD

**Issue by marques-l-GILD** [evilmartians/lefthook#508]
### :wrench: Summary

Lefthook 

### Lefthook version

`1.4.3 41b1cf139772b322400bfcb7754b6cb1c220e6be`

### Steps to reproduce

Add a `pre-push` script that relies on STDIN provided by `git`. For context, `git` passes the following information via STDIN to `pre-push` hooks (per official docs):

```plaintext
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
```

You can simulate this via CLI by running:

```console
$ echo 'refs/heads/main 3a236f32fd701ffda70dd22ea65e61d2670bc1a9 refs/heads/main 0000000000000000000000000000000000000000' | LEFTHOOK_VERBOSE=true lefthook run pre-push origin git@github.com:<my-org/my-repo>.git
```

And of course, substitute the SHAs and remote URL above with valid ones.

If your installed `pre-push` hook is reading STDIN for these values, the script will hang indefinitely because `lefthook` does not forward this to each hook.

### Expected results

`pre-push` hooks should receive STDIN. Valid use cases are tools that scan for secrets being pushed in git history (e.g., [`talisman`](https://github.com/thoughtworks/talisman/tree/main).

### Actual results

`pre-push` hooks that rely on STDIN provided by `git` hang/fail.

**Comment by mrexox** [comment]
Hey! Have you tried [`interactive`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#interactive) and [`follow`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#follow) options?

**Comment by marques-l-GILD** [comment]
@mrexox sadly, it does not work.

Looking at the entry hook that `lefthook` installs, it doesn't even read STDIN to pass them downstream.

For example, in this snippet within `call_lefthook()`:

```bash
  if lefthook -h >/dev/null 2>&1
  then
    eval lefthook $@
```

I would have expected conceptually something more like:

```bash
hookname="$(basename $0)"

if [ 'pre-push' = "$hookname" ]; then
  cat - | eval lefthook "$@"
else
  eval lefthook "$@"
fi
```

And not to mention any golang code that needs to glue STDIN to each `pre-push.scripts.[*]` in `lefthook.yml`.

**Comment by marques-l-GILD** [comment]
@mrexox sure, I might need some time to pull out of a private repo into a public test account with things set up. I probably won't get to that until after my workday, but I'll try to get that done tonight (I'm in pacific time zone).

**Comment by marques-l-GILD** [comment]
@mrexox Ok I created a separate repo with a very simple test case. Instructions are in the README. Do note that you should fork this so you can test the `pre-push` by pushing to a repo you have write access to.

https://github.com/marques-l-GILD/lefthook-pre-push-test

Also, please let me know how I can help, whether it's clarifications, or writing code to help implement/fix this (I just might need some direction on where in the lefthook codebase to look).

Thanks for your help!

**Comment by mrexox** [comment]
Got it, thank you for the repo example. I have checked how it works, and I could make it work with the following config:

```yml
# lefthook.yml

---
pre-push:
  follow: true
  scripts:
    # This is an example script, adapted from .git/hooks/pre-push.sample
    "pre-push.sh":
      runner: sh
    # This is the "real" script I want to run on pre-push
    talisman_hook_script:
      runner: bash
```

However it fails to do `while read ...`, so it supports reading only once (I guess because STDIN is not being closed or whatever). I will dig into this issue and notify you about the progress. Unfortunately, I don't guarantee to do it very soon.

**Comment by marques-l-GILD** [comment]
@mrexox I totally understand you have priorities on top of supporting OSS, so I'm still thankful for the effort of just looking into it. :pray:

**Comment by shining-mind** [comment]
+1 we need this

**Comment by mrexox** [comment]
Hey everyone, I found a cause for this bug – lefthook assumes that `interactive: true` must always connect with tty which is true only when you need to use the tools like [commitzen](https://github.com/commitizen/cz-cli). For scripts and commands that just want to **get an input from stdin** `interactive` will just make it hang, since tty will remain open.

I am going to add a `use_stdin` option (false by default) to pass stdin but do not use tty. Feel free to suggest a better naming. I am planning to release the fix this week.
