### ISSUE TITLE
Git LFS doesn't appear to be working

### ISSUE THREAD

**Issue by stonesbg** [evilmartians/lefthook#511]
### :wrench: Summary

We have lfs setup on our environments and after installing the lefthook hooks it replaces the git lfs hooks.  From the documentation it lefthook does support lfs and if I turn on verbose I can see it try to execute lfs but not sure if there is secret sauce in the lfs hooks but every push doens't include the lfs file upload.

I have tried both wsl2  and windows and both behave the same.  If I remove the lefthook pre-push hooks and re-instate the lfs ones using `git lfs update --force`.  If i push then i can see that the lfs update has triggered.

The only thing I can think of is that potentially would be different execution environment between the two.  I noticed that the hook uses `git-lfs` and the lefthook call uses `git lfs`.  Lastly I also noticed in the hook for windows it does a `unset GIT_PREFIX; ssh git@bitbucket.org 'git-receive-pack '\''brian_garvey/lfs-lefthook-test.git'\'''`

Here is the test repo [LFS Lefthook Test](https://bitbucket.org/brian_garvey/lfs-lefthook-test/src/master/).  I tried to keep it simple.

### Lefthook version

lefthook -> 1.4.3
git -> 2.41.0
git-lfs -> 3.0.2 (WSL 2) & 3.3.0 (windows)

### Steps to reproduce

1. Copy JPG File to directory
2. Install the lefthook hooks `lefthook install -a`
3. Run `git add .` and `git commit -m 'message'`
4. Rung `git push`

### Expected results

LFS images are pushed to the remote repository and and subsequently pull them down

### Actual results

Check bitbucket UI and see that images are not loading and external pull shows 404 errors for the lfs files

### Logs / Screenshots

git hook version
```
trace git-lfs: pure SSH protocol connection failed: Unable to negotiate version with remote side (unable to read capabilities): EOF
trace git-lfs: pre-push: refs/heads/master a92e62630365e8950c18a69b83ab8c141f97a4d8 refs/heads/master eee5ea60a973bde0729800020680bfd928d6be24
trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'show-ref'
trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'ls-remote' '--heads' '--tags' '-q' 'origin'
trace git-lfs: tq: running as batched queue, batch size of 100
````

lefthook version
```
trace git-lfs: pure SSH protocol connection failed: Unable to negotiate version with remote side (unable to read capabilities): EOF
trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'show-ref'
trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'ls-remote' '--heads' '--tags' '-q' 'origin'
trace git-lfs: filepathfilter: creating pattern ".git" of type gitignore
```

**Comment by mrexox** [comment]
Hey! Thank you for the issue. There were always difficulties with LFS because lefthook replaces the hook generated by LFS.

Could you send the output of the `LEFTHOOK_VERBOSE=true git push`?

**Comment by stonesbg** [comment]
Here you go.  I was wondering because there is no STDIN available in lefthook maybe it is appending empty lfs refs and it thinks it has done everything it needs.  

```
❯ git push
Lefthook v1.4.1
RUNNING HOOK: pre-push
[git-lfs] executing hook: git lfs pre-push origin git@bitbucket.org:brian_garvey/lfs-lefthook-test.git
[lefthook] cmd: [git diff --name-only HEAD @{push}]
[lefthook] err: <nil>
[lefthook] out: PH03425I.JPG

[lefthook] files before filters:
[PH03425I.JPG]
[lefthook] files after filters:
[PH03425I.JPG]
[lefthook] files after escaping:
[PH03425I.JPG]
[lefthook] executing: echo 'LFS running'

  EXECUTE > lfs
LFS running


SUMMARY: (done in 11.28 seconds)
✔️  lfs
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 393 bytes | 65.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
To bitbucket.org:brian_garvey/lfs-lefthook-test.git
   02c86d2..2dbbeb7  master -> master
```

**Comment by mrexox** [comment]
Hey! Actually lefthook is just calling what Git LFS adds in the .git/hooks/pre-push with you run `git lfs update --force`. The content I get when running this in the pre-push hook is the following:

```bash
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
git lfs pre-push "$@"
```

So, it calls `git lfs pre-push` with args of the hook. That's exactly [what lefthook does](https://github.com/evilmartians/lefthook/blob/master/internal/lefthook/runner/runner.go#L141-L148).

Could you show what's in your hook after running `git lfs update --force`? Does Git LFS work with LFS-native hooks, without lefthook?

**Comment by avudnez** [comment]
Thanks for the quick response.

> Could you show what's in your hook after running git lfs update --force?

Same as you, the usual git lfs hook.

> Does Git LFS work with LFS-native hooks, without lefthook?

Yes it does, we confirmed it after a `lefthook uninstall`.

**Comment by mrexox** [comment]
>>Does Git LFS work with LFS-native hooks, without lefthook?

>Yes it does, we confirmed it after a lefthook uninstall.

So, it calls the same `git lfs pre-push origin https://remote` but succeedes? 🤔

**Comment by avudnez** [comment]
> So, it calls the same `git lfs pre-push origin https://remote` but succeedes? 🤔

Yes, and as far as I can tell pushing with lefthook installed succeeds, but the objects don't end up on the server which is strange.
Sadly I can't check what's going on when enabling `GIT_TRACE=1` because it makes git error out.

**Comment by mrexox** [comment]
That's weird. I will try to investigate, but please come back with any information you discover.

**Comment by phisko** [comment]
Hi, have you had the chance to take a look at this? Do you have an ETA (even very approximate) on when you might? We've recently migrated from `pre-commit` to `lefthook`, but might have to migrate back if there's no fix on the horizon

(I hope this doesn't sound passive-aggressive, I'm just trying to get a clear picture so we can decide what to do on our end)

**Comment by tdesveaux** [comment]
@mrexox 
Hi, I looked a bit and I believe the issue is that `git lfs pre-push` expect to read commit information on STDIN.
This is documented, here is the first few lines of `git lfs pre-push --help`:
```bash
git lfs pre-push <remote> [remoteurl]

Responds to Git pre-hook events. It reads the range of commits from
STDIN, in the following format:


<local-ref> SP <local-sha1> SP <remote-ref> SP <remote-sha1> \n

```

This issue has an easy reproduction in a repository with pre-push hooks.
After a push of a new/updated LFS file, simply run: `rm -rf .git/lfs/ && git lfs fetch origin HEAD`

**Comment by tdesveaux** [comment]
Try adding a dumb `cmd.Stdin = os.Stdin` in execute_unix.go `RawExecute` and it works now.
I believe it's not a proper solution as if another hook needs the information from stdin, execution order will let the first hook work as expected, and others fail.

Lefthook should probably read stdin and provide it to all hooks as needed.

**Comment by mrexox** [comment]
@tdesveaux , it makes sense to me. Thank you for checking the RawExecute method. I agree that all hooks should receive the same STDIN in case of pre-push hook. 

I will try to think out this feature. The only complication here is that some commands may be executed in interactive mode, so we can't just read STDIN into a buffer for them. But I guess this is anyway feasible to find a workaround.

**Comment by tdesveaux** [comment]
If I can suggest a quick "fix" for the moment.
Since you already have the [`use_stdin`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#use_stdin) option for commands, you could throw an error if a pre-push command has it to true when LFS is also detected?

This way, you can add `cmd.Stdin = os.Stdin` to `RawExecute` and fix LFS push.
The feature to have multiple commands that need stdin can be implemented later on.

I'm not knowledgeable on the lefthook codebase at all, so this might not be possible.

If this suggestion is fine with you, I could try to implement it.

**Comment by mrexox** [comment]
I like your suggestion. I'd be glad to receive a PR with this fix :+1:

**Comment by mrexox** [comment]
Please, check lefthook release **1.6.14**. Feel free to re-open this issue if you notice any problems with LFS.
