### ISSUE TITLE
Add Swift Plugin support

### ISSUE THREAD

**Issue by csjones** [evilmartians/lefthook#544]
### :zap: Summary

Thank you for making such an exceptional tool. While I primarily develop in Swift, I've recently created a wrapper plugin for Lefthook that can be included in Swift packages.

https://github.com/csjones/lefthook

### Value

Direct Swift Package Manager support instead of relying on installation methods like go get, brew, npm, or gem.

### Behavior and configuration changes

At minimum, the primary change would be in the `hooks.tmpl` file:

```bash
  elif swift package plugin lefthook >/dev/null 2>&1
  then
    swift package --disable-sandbox plugin lefthook $@
  else
```

Additional changes are dependent on whether it makes sense for a Swift plugin to live along side npm and rubygems implementations in this repository. This would include a `Package.swift` manifest file in the root of the repository and CI additions to create a `lefthook.artifactbundle.zip` file.

Alternatively, I could create a wrapper plugin package that downloads the Lefthook release binaries and implements all the swift details in a separate repository.

**Comment by csjones** [comment]
I've investigated and implemented the wrapper plugin approach here: https://github.com/csjones/lefthook-plugin

So far, the lefthook swift plugin is working well on macOS and Linux.

**Comment by mrexox** [comment]
Hey @csjones, this is amazing! Do you want to keep your plugin in your repo or integrate it into lefthook repo?

**Comment by csjones** [comment]
Hey @mrexox, now having tried both approaches, I'm leaning more towards the plugin in the repo I created than the lefthook repo. Should I open a PR for the changes to `hooks.tmpl`?

**Comment by mrexox** [comment]
@csjones , yes, that will be great. It would be also good to add a note into `docs/installation.md` and reference your repo there

**Comment by csjones** [comment]
@mrexox done!
