### ISSUE TITLE
Cannot force command to run with --all-files unless using `{files}`

### ISSUE THREAD

**Issue by sanmai-NL** [evilmartians/lefthook#554]
### Lefthook version

1.5.0

### Steps to reproduce

`.lefthook.yml`:

```yaml
---
pre-push:
  commands: &pre-push
    pdm-lock:
      files: git ls-files pyproject.toml
      run: pdm lock --group ':all' --refresh
  parallel: true
```

### Expected results

When invoked manually, commands are always run, regardless of template occurrence in the command line.

### Actual results

1. The `pre-push` hook needlessly checks whether there is something to push, even when invoked manually.
2. When a `{files}` template is used in the command line, the check whether there is something to push is suddenly skipped and the command _is_ run, however.

### Possible Solution

When invoked manually, commands are always run, regardless of template occurrence in the command line.

### Logs / Screenshots

```console
$ lefthook run -v pre-push --commands pdm-lock --all-files
│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: /Users/sanderhan/devel/gitlab.com/han-aim/tools
                                                               
│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks
                          
│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info
                         
│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: .git
                    
╭────────────────────────────────────╮
│ 🥊 lefthook v1.5.0  hook: pre-push │
╰────────────────────────────────────╯
│ [git-lfs] executing hook: git lfs pre-push 
│ [git-lfs] out: This should be run through Git's pre-push hook.  Run `git lfs update` to install it.
│ [git-lfs] err: exit status 1
│ [lefthook] cmd: [sh -c git ls-files pyproject.toml]
│ [lefthook] dir: /Users/myuser/repo
│ [lefthook] err: <nil>
│ [lefthook] out: pyproject.toml
                              
│ [lefthook] files before filters:
[pyproject.toml]                
│ [lefthook] files after filters:
[pyproject.toml]               
│ [lefthook] cmd: [sh -c git diff --name-only HEAD @{push}]
│ [lefthook] dir: /Users/myuser/repo
│ [lefthook] err: <nil>
│ [lefthook] out: 
│  pdm-lock (skip) no matching push files
                                      
  ─────────────────────────
```

When a (dummy) `{files}` template is used, the command _is_ run, however.

```yaml
# ...
run: pdm lock --group ':all' --group '{files}' --refresh
# ...
```

```console
$ lefthook run -v pre-push --commands pdm-lock --all-files
│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: /Users/myuser/repo
                                                               
│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks
                          
│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info
                         
│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: .git
                    
╭────────────────────────────────────╮
│ 🥊 lefthook v1.5.0  hook: pre-push │
╰────────────────────────────────────╯
│ [git-lfs] executing hook: git lfs pre-push 
│ [git-lfs] out: This should be run through Git's pre-push hook.  Run `git lfs update` to install it.
│ [git-lfs] err: exit status 1
│ [lefthook] cmd: [sh -c git ls-files pyproject.toml]
│ [lefthook] dir: /Users/myuser/repo
│ [lefthook] err: <nil>
│ [lefthook] out: pyproject.toml
                              
│ [lefthook] files before filters:
[pyproject.toml]                
│ [lefthook] files after filters:
[pyproject.toml]               
│ [lefthook] files after escaping:
[pyproject.toml]                
│ [lefthook] executing: pdm lock --group ':all' --group 'pyproject.toml' --refresh
┃  pdm-lock ❯ 

Ignoring non-existing groups: pyproject.toml
Changes are written to pdm.lock.

                                      
  ────────────────────────────────────
summary: (done in 2.90 seconds)       
✔️  pdm-lock
```

**Comment by mrexox** [comment]
Hey, in v1.5.1 I've added a `--force` flag, so you can use `lefthook run pre-push --force` if you don't want the command to be skipped.

I think it would be a bad design to distinguish between manual run and hook-triggered run. However it is not impossible.

**Comment by sanmai-NL** [comment]
@mrexox `--force` now runs commands with empty file lists if nothing is staged. Furthermore `--force` with `--all-files` runs all commands with all files. I don‘t see how how these behaviors are ever useful.

I requested to be able to run a hook with either all files or the staged files, per the hook configuration, regardless of the name of the hook (`pre-push` now behaves differently from `foo`).

**Comment by mrexox** [comment]
@sanmai-NL , I understand your case. There is an implicit check in `pre-commit` and `pre-push` hooks that skip execution if `{staged_files}` or `{push_files}` are empty respectively. This behavior was added for convenience, so people could omit using `{files}` with filters when they actually mean staged files and pushed files.

It looks like you want to use lefthook for manual hooks without those tweaks. I can suggest you to use the YAML anchors:

```yml
checks:
  files: <a custom command for files whether it is staged files or push files >
  commands: &checks
    pdm-lock:
      glob: <here you can specify any filters>
      run: pdm lock --group ':all' --refresh
    # ...

pre-push:
  commands: *checks # here push files will be used implicitly

pre-commit:
  commands: *checks # here staged files will be used implicitly
```

So, you use git hooks when calling lefthook implicitly and custom hooks when calling explicitly via `lefthook run`. Does it work for you?

**Comment by sanmai-NL** [comment]
@mrexox That doesn't pick up other settings of the hook, like `parallel`.

I don't really see the logic of that convenience. Was there a problem for users?

**Comment by mrexox** [comment]
There were the following issues:

- https://github.com/evilmartians/lefthook/issues/228
- https://github.com/evilmartians/lefthook/issues/441
- https://github.com/evilmartians/lefthook/issues/446

> That doesn't pick up other settings of the hook, like `parallel`.

Could you share your requirements, so I could think out a proper configuration?
