### ISSUE TITLE
pre-commit hook always warns "Couldn't hide unstaged files: exit status 1"

### ISSUE THREAD

**Issue by Crissante** [evilmartians/lefthook#573]
### :wrench: Summary

When committing a change and the pre-commit hook runs, the warning "Couldn't hide unstaged files: exit status 1" is always printed

### Lefthook version

1.5.2

### Steps to reproduce

1. Open project with a pre-commit hook
2. Commit some changes

### Expected results

No warning is printed

### Actual results

The warning "Couldn't hide unstaged files: exit status 1" is printed on every commit

**Comment by scop** [comment]
`LEFTHOOK_VERBOSE=true` in the environment could reveal something for someone to work on this, please note that part of the issue report template, too: https://github.com/evilmartians/lefthook/blob/736ac31d15af4b9c020efdcdb48c2c128c892e86/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L31-L36

**Comment by Crissante** [comment]
Here's where the errors occurs @scop

```
│ [lefthook] cmd: [git checkout --force -- main...origin/main]
│ [lefthook] dir: /Users/john/repos/resum
│ [lefthook] err: exit status 1
│ [lefthook] out: error: pathspec 'main...origin/main' did not match any file(s) known to git
                                                                                           
Couldn't hide unstaged files: exit status 1
```

**Comment by mrexox** [comment]
@Crissante, could you please provide the full log? Also, what Git version do you currently use?

**Comment by mrexox** [comment]
No response for a long time. Closing this issue. Please feel free to write a comment with more logs and I will reopen the issue.
