### ISSUE TITLE
`--no-colors` does not disable all colorized output

### ISSUE THREAD

**Issue by scop** [evilmartians/lefthook#581]
### :wrench: Summary

Per the subject.

### Lefthook version

1.5.2 

### Steps to reproduce

```
lefthook --no-colors run pre-commit --all-files
```

### Expected results

No colors in output, just the configured terminal colors.

### Actual results

Some colors remain, e.g. in the lefthook icon and the last summary line status icon.

### Logs / Screenshots

![Screenshot from 2023-11-17 18-20-50](https://github.com/evilmartians/lefthook/assets/109152/e9562b08-4b83-43db-896f-858ff7d50449)

**Comment by mrexox** [comment]
Hey! `--no-colors` option wasn't supposed to disable icons 🤔 Do you disagree?

**Comment by scop** [comment]
It is currently documented as "disable colored output", so I thought it'd apply to all colors, no matter the implementation detail whether that's marked up or part of an icon.

With the current description I'd say this is a bug, but the fix might be to fix the description, for example "disable colored text output".

Then again, I don't know if there's a deeper reasoning _why_ colors are disabled, and if it's about colors or some escape sequences that might not work nicely everywhere. But if it's about _colors_ in particular, then I'd think colors should be disabled no matter where they come from.

Not a biggie at all though, just a bit surprising.

**Comment by mrexox** [comment]
Hmm, probably some subcommands use colorized output?

**Comment by mrexox** [comment]
I hope that PR https://github.com/evilmartians/lefthook/pull/812 will fix the color-specific issues
