### ISSUE TITLE
Add option to force colorized output

### ISSUE THREAD

**Issue by scop** [evilmartians/lefthook#582]
### :zap: Summary

An option to force colorized output would be nice. For example when running in GitHub Actions, the output is color capable but lefthook does not currently colorize there.

### Value

More color and arguably readability in CI logs when lefthook is run there.

### Behavior and configuration changes

Would probably be a good idea to deprecate the existing `--no-colors` flag and add a new `--color={on,off,auto}` to replace it.

**Comment by mrexox** [comment]
Hey! There's a config option for that instead – [`colors`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#colors). I don't think CLI option would be really useful, since lefthook is supposed to be executed implicitly by git hook.

Do you use lefthook in CI? Could you share your use case please?

**Comment by scop** [comment]
I do use (well plan to use) lefthook in CI. Use case is: run exactly same things on developer systems and in CI. Same versions of everything, same config of everything. [pre-commit](https://pre-commit.com) works great for that, but has some other not so great parts that I'd hope lefthook will help fix.

Lefthook does not have builtin help for "same versions of everything" e.g. installing things which pre-commit does have (and that's its killer feature), but I have a hatching project at https://github.com/scop/wrun which will help with that in some cases. Some WIP dogfooding using lefthook at https://github.com/scop/wrun/pull/49 -- this same thing runs both in CI and locally.

**Comment by scop** [comment]
Regarding the config option, I guess I could make do with that and set up different config files for CI and local dev, but that's IMO really an antipattern I'd like to avoid having to do by default. In CI we need to invoke lefthook manually, and dropping e.g. `--colors=on` there would fit in great.

**Comment by scop** [comment]
Regarding CI usage, here's pre-commit's related docs: https://pre-commit.com/#usage-in-continuous-integration

In my experience, this use case for pre-commit (and other hook managers) is not at all uncommon, there are _lots_ of repositories e.g. here at GitHub that are set up to run the same hooks locally and in GH Actions.

**Comment by scop** [comment]
I found that the indirect termenv dependency supports CLICOLOR_FORCE for this. I'm not sure if it's equal to forcing all color from lefthook, but it's a good start and enough for me for the time being: https://github.com/muesli/termenv?tab=readme-ov-file#usage

Example CI run at https://github.com/scop/wrun/actions/runs/10602871399/job/29385896528 ("Run lefthook pre-commit")

If considering implementing direct support for env based color toggles in lefthook, here are the "strandards" to look into
- https://no-color.org
- https://force-color.org
- https://bixense.com/clicolors/

Currently the said github.com/muesli/termenv and github.com/fatih/color indirect deps have some support for these.

**Comment by scop** [comment]
Sorry, this went unnoticed by me, late thanks!
