### ISSUE TITLE
Not just `skip_output`, specify `output` explicitly

### ISSUE THREAD

**Issue by sanmai-NL** [evilmartians/lefthook#592]
### :zap: Summary

Currently, it's only possible to further reduce output rather than increase it.

### Value

I want to see which commands were executed, e.g., `execution_info` to help my users and to debug issues.

### Behavior and configuration changes

Deprecate `skip_output` and change it to `output` which is an explicit positive/allowlist of outputs.

**Comment by mrexox** [comment]
It makes sense! Thank you for submitting a feature request!
