### ISSUE TITLE
pre-push hook fails in v1.5.5 but works in v1.5.4 for some cases

### ISSUE THREAD

**Issue by hustcer** [evilmartians/lefthook#600]
### :wrench: Summary

pre-push hook fails in v1.5.5 but works in v1.5.4 for some cases

### Lefthook version

1.5.5 9b072e6622857ceb8d40a173ba39ae97afb35957

### Steps to reproduce

I have tried the latest version of lefthook in https://github.com/hustcer/setup-nu repo:

![lefthook-issue](https://github.com/evilmartians/lefthook/assets/1161607/396bd9ae-a2bb-43d4-8ba9-42acf347df40)

The output of 1.5.5 does't look like 1.5.4, notice that this part is missing:

```console
refs/heads/main e7fd469233d16703a7060d7b14feae806720659b refs/heads/main 26a18e5e4802a087f12cfcd83b832db8c2b1d07a
Pushing to remote...
----------------------------------
```

### Expected results

1.5.5 should work the same as 1.5.4

### Logs / Screenshots

```bash
LEFTHOOK_VERBOSE=true git ...
```

**Comment by mrexox** [comment]
You are right. There was a change introduced in 1.5.5 - https://github.com/evilmartians/lefthook/pull/590. Lefthook doesn't implicitly pass STDIN to subcommands/scripts. To fix this please use `use_stdin: true` option explicitly.

I forgot that this might be a breaking change. Do you have problems after this change?

**Comment by hustcer** [comment]
That works for me, thanks.
