### ISSUE TITLE
Wiki still mentions previous owner

### ISSUE THREAD

**Issue by infotexture** [evilmartians/lefthook#605]
Wiki editing is apparently restricted to users in teams with push access, so I can't fix this myself, but in various places the wiki still mentions @arkweid as package owner, so following instructions in the wiki throws warnings.

For example, [Migration from husky](https://github.com/evilmartians/lefthook/wiki/Migration-from-husky) and [Migration from husky with lint staged](https://github.com/evilmartians/lefthook/wiki/Migration-from-husky-with-lint-staged) both say to install via  
`npm install @arkweid/lefthook --save-dev`, but:

```
npm install @arkweid/lefthook --save-dev
npm WARN deprecated @arkweid/lefthook@0.7.7: @arkweid/lefthook has been renamed to @evilmartians/lefthook, 
please upgrade to it. You also can use @evilmartians/lefthook-installer
```

Makes me wonder how up-to-date the rest of the info there is. 🤔 

For Husky migrations, there's no mention of removing things like the `.husky/pre-commit` hook that recent Husky versions install, so I'm left wondering whether these instructions were written for older Husky versions.

Wiki pages [include](https://github.com/evilmartians/lefthook/wiki/Migration-from-husky#more-info) a footer that points to `Arkweid/lefthook/wiki`:

> ### More info
> 
> Have a qustions? Check the [wiki](https://github.com/Arkweid/lefthook/wiki).

**Comment by mrexox** [comment]
Thank you for creating this issue. Yes, wiki is rather stale and needs the complete rework. I will either hide it for some time or rewrite some pages, so it doesn't confuse people.
