### ISSUE TITLE
interactive mode doesn't work on Windows.

### ISSUE THREAD

**Issue by ianzone** [evilmartians/lefthook#621]
reproduction repo: https://github.com/ianzone/node-template
execute git commit on Windows PowerShell. 

```PowerShell
> git add . && git commit

╭───────────────────────╮
│ 🥊 lefthook v1.6.1  hook: prepare-commit-msg │
╰───────────────────────╯
┃  commitzen ❯


  ──────────────────
summary: (done in 0.01 seconds)
🥊  commitzen
```

**Comment by SIOFOYER** [comment]
I add the same issue with commitizen too. It's due to Windows directcly because if you run `lefthook run prepare-commit-msg` it will works

**Comment by mrexox** [comment]
Thank you! I will investigate the problem. I think the problem is that lefthook does not open a TTY for interaction when used on Windows. I will try to find a solution for this.

**Comment by SIOFOYER** [comment]
I wrote a bit more details here : https://github.com/evilmartians/lefthook/issues/125#issuecomment-2031375811

**Comment by mrexox** [comment]
Please, check **1.6.9** release. I've fixed this issue in there. Please, write back or create a new issue if it does not work.

**Comment by SIOFOYER** [comment]
[1.6.10] Rendering is different from cz default command. (No colors). Also, each time you navigate or make a selection, it duplicate all lines.

thx

**Comment by SIOFOYER** [comment]
1.6.12 works well. Thank you 👍
