### ISSUE TITLE
Unable to process files with a $ in their path

### ISSUE THREAD

**Issue by eikowagenknecht** [evilmartians/lefthook#651]
### :wrench: Summary

Mostly the same as #303, but instead of 
`No files matching the pattern "some/path/to..tsx" were found.`  I get
`No files matching the pattern "'some/path/$file.tsx'" were found.`

I'm using Windows.

### Lefthook version

1.6.3 0845abb2105d2e6870744915df8445af00afd0c0

### Steps to reproduce

1. Have a file with `$` in its name.
2. Run lefthook

lefthook.yml:
```yaml
pre-commit:
  parallel: false
  commands:
    eslint:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx}"
      run: npx eslint {staged_files}
```

### Expected results

File is processed.

### Actual results

```
Oops! Something went wrong! :(

ESLint: 8.57.0

No files matching the pattern "'src/routes/manage/$cardId.tsx'" were found.
Please check for typing mistakes in the pattern.
```

### Possible Solution

It seems like there are too many quotes arount the staged files. From the console:

- `npx eslint 'src/routes/manage/$cardId.tsx'` -> works
- `npx eslint "src/routes/manage/$cardId.tsx"` or `npx eslint src/routes/manage/$cardId.tsx` -> `No files matching the pattern "src/routes/manage/.tsx" were found.`

### Logs / Screenshots

```bash
...
│ [lefthook] out: lefthook.yml
src/routes/manage/$cardId.tsx

│ [lefthook] files before filters:
[lefthook.yml src/routes/manage/$cardId.tsx]
│ [lefthook] files after filters:
[src/routes/manage/$cardId.tsx]
│ [lefthook] files after escaping:
['src/routes/manage/$cardId.tsx']
│ [lefthook] executing: npx eslint 'src/routes/manage/$cardId.tsx'
⠇ waiting: eslint-fix
Oops! Something went wrong! :(

ESLint: 8.57.0

No files matching the pattern "'src/routes/manage/$cardId.tsx'" were found.
Please check for typing mistakes in the pattern.
...
```

I especially notice the line `[lefthook] executing: npx eslint 'src/routes/manage/$cardId.tsx'`, which is exactly what I run from the console. And there it works?

This issue documents the problem for eslint only, but I have the same problem with Biome for example, where a "  × The system cannot find the path specified. (os error 3)" error is thrown instead of the message eslint gives. For this as well, running  `npx biome check --apply --no-errors-on-unmatched --files-ignore-unknown=true 'src/routes/manage/$cardId.tsx'` from the console works fine.

The suggested workaround 

```
    eslint-fix:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx}"
      run: node_modules/.bin/eslint {staged_files}
```

does not work for me and only gives the error message `'node_modules' is not recognized as an internal or external command, operable program or batch file.`

**Comment by mrexox** [comment]
Thank you for the issue. I think the problem occurs because for windows the argument includes the quotes, while on Linux/macOS those quotes are treated differently because the actual command is wrapped with `sh`. Currently I don't have a workaround for this issue, but I will try to figure it out.

**Comment by wonu** [comment]
`"{staged_files}"` works, `'{staged_files}'` causes the same error.

**Comment by mrexox** [comment]
@eikowagenknecht , does wrapping {staged_files} in `"` helps?

```yml
pre-commit:
  parallel: false
  commands:
    eslint:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx}"
      run: npx eslint "{staged_files}"
```

**Comment by eikowagenknecht** [comment]
Indeed, `"{staged_files}"` fixes it :-)

**Comment by mrexox** [comment]
I'm closing this issue since there's a workaround found. Thank you, @wonu!

**Comment by eikowagenknecht** [comment]
Weird, after a Windows reinstallation, now I have to use `'staged_files'` instead of `"staged_files"`.

**Comment by mrexox** [comment]
Oh, it can be, I've recently release a new version of lefthook with some fixes for Windows. Does it wotk with `'{staged_files}'` now?

**Comment by eikowagenknecht** [comment]
Ah, then that might have changed it. Currently it works with single quotes 👍
