### ISSUE TITLE
Case-insensitive glob?

### ISSUE THREAD

**Issue by asmaloney** [evilmartians/lefthook#68]
Is there a way to make `glob` case-insenstive?

It would avoid having to write:

```yaml
glob: "*.{jpg,JPG,Jpg,jPg,jpG,JPg,jPG}"
```

(I hope nobody uses those extensions, but you get the idea. 😀)

**Comment by Arkweid** [comment]
Hello, we using this: https://github.com/gobwas/glob `glob` library. It is worth looking there.

**Comment by asmaloney** [comment]
The response I got was "It's easy to case fold / lowercase the pattern and match string before matching.", so it would require a change on the lefthook side.
