### ISSUE TITLE
npm: Not working with bun without node

### ISSUE THREAD

**Issue by cethien** [evilmartians/lefthook#688]
### :wrench: Summary

seems like the tool doesn't work without node. i have only [bun](https://bun.sh) for js on my system. 
after `lefthook install`, every hooked git actions results in `/usr/bin/env: ‘node’: No such file or directory`

### Lefthook version

1.6.7 599459eb87d1dab4fd56707fd1ad3a4209c133c8

### Steps to reproduce

```bash
curl -fsSL https://bun.sh/install | bash
cd <repo>
bun add -D lefthook
<define any lefthook action, eg. commitlint>
lefthook install
git add . && git commit -m "hello"
```

### Expected results

commitlint error

### Actual results

/usr/bin/env: ‘node’: No such file or directory

### Logs / Screenshots

```bash
+ '[' '' = 0 ']'
+ call_lefthook run prepare-commit-msg .git/COMMIT_EDITMSG message
++ git rev-parse --show-toplevel
+ dir=<userprofile>/source/posh-nv
++ uname
++ tr '[:upper:]' '[:lower:]'
+ osArch=mingw64_nt-10.0-22631
++ uname -m
++ sed s/aarch64/arm64/
+ cpuArch=x86_64
+ test -n ''
+ lefthook.exe -h
+ lefthook.bat -h
+ test -f <userprofile>/source/posh-nv/node_modules/lefthook/bin/index.js
+ <userprofile>source/posh-nv/node_modules/lefthook/bin/index.js run prepare-commit-msg .git/COMMIT_EDITMSG message     
/usr/bin/env: ‘node’: No such file or directory
```

**Comment by dalisoft** [comment]
@mrexox @cethien #705 maybe fixes this case as [removes](https://github.com/evilmartians/lefthook/pull/705/files) require of Node.js and `#!/usr/bin/env node`

**Comment by Blaquewithaq** [comment]
For those of you, that want to utilize this package with bun now, Ive figured out a quick patch solution until bun support has been officially added.

Add these to your package.json file and you'll be good to go. 
```
"prepare:lefthook": "lefthook install && bun -e \"const fs=require('fs'); fs.writeFileSync('node_modules/lefthook/bin/index.js', fs.readFileSync('node_modules/lefthook/bin/index.js', 'utf8').replace(/^#!\\/usr\\/bin\\/env\\s+node/gm, '#!/usr/bin/env bun'))\"",
		"postinstall": "bun prepare:lefthook"
```

**Comment by dy0gu** [comment]
@Blaquewithaq, thanks for the temporary fix!

Any news on if @dalisoft's PR removes the node dependency to allow runtime independence? Using the above solution is a whole lot of verbose that would be amazing to clear up.

**Comment by cethien** [comment]
since I opened the issue, I was experimenting around a bit and observed something useful:

when installing other tools like [esbuild](https://github.com/evanw/esbuild), there is no js script that executes the binary, only a script to install for the right OS.
the root cause for my problem seems to be the js script that runs the binary - is it possible to ditch the index.js alltogether?

**Comment by mrexox** [comment]
I hope so, I have @dalisoft's PR on my radar, I just need to test it to make sure it solves the issue with bun.

**Comment by dy0gu** [comment]
> I hope so, I have @dalisoft's PR on my radar, I just need to test it to make sure it solves the issue with bun.

Hey @mrexox, it seems you have merged the PR you referred to here, do you have any updates on this issue? Can it be closed, or are there any extra steps that need to be taken?

**Comment by mrexox** [comment]
Hey! Unfortunately there was a backward compatibility issue with the PR, I am going to try a slightly different approach and will notify ASAP.

**Comment by mrexox** [comment]
@cethien could you please check if the newest lefthook version works? I've changed the order of checks in the hook template and it must not fail with `/usr/bin/env: ‘node’: No such file or directory`

**Comment by cethien** [comment]
> @cethien could you please check if the newest lefthook version works? I've changed the order of checks in the hook template and it must not fail with `/usr/bin/env: ‘node’: No such file or directory`

hey, only managed to test now

I removed node from my system, and tested this one:

.lefthook.yml
```yaml
# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

commit-msg:
  parallel: true
  commands:
    commitlint:
      run: bun commitlint --edit $1
```

it seemed to work, my commit was some gibberish and i got a commitlint error.

**Comment by cethien** [comment]
seems to be resolved

**Comment by sjiamnocna** [comment]
Hello again.
Time to time I try to move my Dockerfile from node:alpine to bun:alpine. But it failed with "env: can't execute 'node': No such file or directory".

So I've done
`docker run -it oven/bun:alpine sh`
`$: bun i -g @localazy/cli`
The result is the same and I found this bug:
> `env: can't execute 'node': No such file or directory`

What should I do to run the Next app with all deps in Bun:alpine container correctly?

**Comment by raiomarco** [comment]
> Right now there is no way to do this other than installing lefthook from a different source (e.g. alpine registry). This is because postinstall hook of the npm package requires node

i don't think it's the case, because it works with husky (at least for me), so this problem is related to lefthook... i will do some testing and try to understand more about the exact root cause
