### ISSUE TITLE
Feature Requests: Lint only changed lines, not whole files; Warn, don't Fail

### ISSUE THREAD

**Issue by nmagedman** [evilmartians/lefthook#69]
Thanks for your amazing work, Alexander!

I have a large, legacy codebase riddled with RuboCop offenses.  I want to introduce RuboCop into our development pipeline _gradually_.

I'm interested in having RuboCop lint files when committing them, with two caveats:
1. Only lint modified _lines_, not the entire file.  That is, ignore errors on lines that were not changed this commit.
2. Don't _abort_ the commit; just show the warnings but allow the commit to continue.

Overcommit implements both of these:
1. `problem_on_unmodified_line: {report,warn,ignore}`
2. `on_fail: warn`

Using Lefthook, I can achieve the effect of # 2 within the linter itself: `rubocop --fail-level=E`, or perhaps by replacing the 1-line call to rubocop with a script that always returns true.

However, how can I achieve the effect of # 1?

**Comment by Arkweid** [comment]
Right now such kind of behavior can be achieved with custom script in the same way like `overcommit` it does.

The hard way:
1. Get `git diff` and extract modified line numbers, store it in some `array` struct;
2. Run `rubocop`, capture `stdout` and extract line with errors, store it in some `array` struct;
3. Find intersection between this two arrays. Return `exit status 1`, if some intersection present.

The easy way.
1. Run `rubocop` and extract number of errors.
2. Store number of errors in simple text file.
3. After that, reject commits if `rubocop` return more than stored in file count of errors. Else update the less number of errors.

**Comment by pbstriker38** [comment]
@nmagedman You could use [Pronto](https://github.com/prontolabs/pronto) with the Rubocop runner. The following will only compare staged changes.
```
pre-commit:
  parallel: true
  commands:
    pronto:
      tags: lint style
      run: bundle exec pronto run --staged --exit-code
```

if you remove `--exit-code` it will print out the issues but will not block the commit.

**Comment by mrexox** [comment]
Must be working on latest lefthook versions. Lefthook automatically stashes the unstaged changes in pre-commit hook and reverts them after.
