### ISSUE TITLE
"no matching staged files" error when I ran "pre-commit" manually

### ISSUE THREAD

**Issue by yuseferi** [evilmartians/lefthook#712]
### :wrench: Summary
When I want to run my "pre-commit" manually with "lefthook run pre-commit" it returns "no matching staged files" which shouldn't be like this, because I run it manually it it should not be sensetive on stage/unstage status of file.

### Lefthook version

1.6.10

### Steps to reproduce

create a pre-commit, and try to run it manually

### Expected results

pre commit should be run

### Actual results

"no matching staged files"

### Possible Solution

when run comes from the manual source do ignore stage/unistage file situation

**Comment by mrexox** [comment]
Hey! You can use `--force` option that will omit the filters if you have them (like `glob`, `exclude`). Or you can run the pre-commit hook against all files, so any of these may work:

```bash
# Agains all staged files without filtering
lefthook run pre-commit --force

# Agains all files
lefthook run pre-commit --all-files --force
```

Or if these options don't work for you, could you share your lefthook config, so I could think out a possible solution?

**Comment by yuseferi** [comment]
Thank you for the quick reply. I will close this 🙏
