### ISSUE TITLE
Error message when lefthook is older could include more info

### ISSUE THREAD

**Issue by technicalpickles** [evilmartians/lefthook#718]
### :zap: Summary

If you have a `min_version` in lefthook.yml, and try to run a hook using it, you get a failure like:

```
Error: required Lefthook version is higher than current
```

I'd propose adding some info like:

- the current version running
- the version requested
- the path of lefthook that is running

### Value

This would make it easier to help someone figure out why it's failing.

One example I have run into is with having both homebrew and gem installed lefthook... if you use `rbenv` or another shim based ruby version manager, you typically would have that on the PATH before a homebrew installed one, and it's really easy for those to get out of sync.

**Comment by mrexox** [comment]
That's a good improvement! Thank you. I will try to achieve this but your PR is also welcome.
