### ISSUE TITLE
fetch new scripts automatically when remote scripts changed

### ISSUE THREAD

**Issue by SirNoSir** [evilmartians/lefthook#736]
### :zap: Summary
It will be great that lefthook can fetch new scripts automatically when remote scripts changed.

### Value

We use remotes feature to manage scripts. If lefthook support fetch scripts automatically, we just release our scripts and Inform our developers what is new, our developers don't need to execute install command every time.

### Behavior and configuration changes
add configuration option under remotes option with default value false.just like this:

```
remotes:
  - git_url: https://github.com/evilmartians/lefthook
    refetch: true
```
when the value was set true, lefthook will refetch of the code every call.

**Comment by mrexox** [comment]
Hey @SirNoSir, please, check out lefthook **1.6.15**, where this feature was added.

If you find any issues or missing features, I'd be glad to help!
