### ISSUE TITLE
Missing prepare-commit-msg hook type

### ISSUE THREAD

**Issue by vkrol** [evilmartians/lefthook#74]
Hello.

First of all, thank you very much for Lefthook! There are about 60 people in our team who commit to our mono repository. We recently migrated to Lefthook to manage the hooks. We chose between Overcommit, Husky, pre-commit and a few other alternatives and decided on Lefthook.

I've discovered that `prepare-commit-msg` hooks are not supported. I found this commit https://github.com/Arkweid/lefthook/commit/24bd1f74bbbae18ac96da56d0cced2e1c44d089e, but I can't find any information about why this change was made. Could you clarify, please?

**Comment by Arkweid** [comment]
Hello @vkrol
We use it to synchronize the configuration file. So every time when you change `lefthook.yml` for example add a new hooks group, you don't need to run `lefthook install`. New hooks will be added automatically in `.git/hooks`.
Probably no the best solution :sweat_smile:

**Comment by vkrol** [comment]
Thank you for the explanation! At the moment, we are using `commit-msg` instead of `prepare-commit-msg`, but it would be nice if `prepare-commit-msg` would also be supported. If I have ideas, then I will share them.

What do you think about adding a note about this to the documentation?

**Comment by Arkweid** [comment]
> What do you think about adding a note about this to the documentation?
For sure, good point.

**Comment by Arkweid** [comment]
@vkrol should be fixed in 0.6.4

**Comment by vkrol** [comment]
@Arkweid If I'm not mistaking anything, it doesn't work in 0.6.4. And that condition has also remained unchanged https://github.com/Arkweid/lefthook/blob/master/cmd/run_windows.go#L101.

**Comment by Arkweid** [comment]
Ah, sorry. You right.

**Comment by skryukov** [comment]
I've tested `prepare-commit-msg` with `v0.7.5` and it works ok, so i'll close the issue for now. Feel free to ping me if it does not work in your case.

**Comment by vkrol** [comment]
@skryukov Yes, it works. Thanks!
