### ISSUE TITLE
1.6.16 not available in apt/rpm repos

### ISSUE THREAD

**Issue by scop** [evilmartians/lefthook#749]
### :wrench: Summary

SSIA. https://cloudsmith.io/~evilmartians/repos/lefthook/packages/ has up to 1.6.15 only.

### Expected results

1.6.16 in repos.

### Logs / Screenshots

```bash
LEFTHOOK_VERBOSE=true git ...
```

**Comment by mrexox** [comment]
Thank you! My bad, I forgot to upload the packages. They should be available now!
