### ISSUE TITLE
git commit command with error in macos `14.4.1` for M3.

### ISSUE THREAD

**Issue by KomachiSion** [evilmartians/lefthook#775]
### :wrench: Summary

git commit command with error in macos `14.4.1` for M3.

```
╭──────────────────────────────────────╮
│ 🥊 lefthook v1.7.3  hook: pre-commit │
╰──────────────────────────────────────╯
npx: installed 1 in 1.106s
npx: command not found: lefthook-darwin-x64
```

### Lefthook version

```
 npx lefthook version 
1.7.3
```

### Steps to reproduce

run git commit command with lefthook 1.7.3

### Expected results

commit successfully

### Actual results

error: `npx: command not found: lefthook-darwin-x64`

### Possible Solution

force downgrade to 1.7.2.
```
npm install lefthook@1.7.2 --save-dev
```

### Logs / Screenshots

```
19:58:44.675: [nacos] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false checkout HEAD -- pom.xml
19:58:57.931: [nacos] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- pom.xml
19:58:57.985: [nacos] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -F /private/var/folders/yj/8c9m_w0s4hv6zvryj59r75lr0000gp/T/git-commit-msg-.txt --
╭──────────────────────────────────────╮
│ 🥊 lefthook v1.7.3  hook: pre-commit │
╰──────────────────────────────────────╯
npx: installed 1 in 1.106s
npx: command not found: lefthook-darwin-x64
```

**Comment by luizwhite** [comment]
similar issues here https://github.com/evilmartians/lefthook/issues/773
I replied that the error still occurs

**Comment by amochkin** [comment]
Try 1.6.19, hope it helps.

**Comment by KomachiSion** [comment]
I think this bug is from PR https://github.com/evilmartians/lefthook/pull/774. 

but https://github.com/evilmartians/lefthook/pull/774 close #733, maybe different.

**Comment by KomachiSion** [comment]
> Try 1.6.19 or 1.6.18, hope it helps.

I force downgrade to 1.7.2, it work well.
Before 1.7.3 released and auto-upgrade, git commit never failed.

**Comment by mrexox** [comment]
Hey! Please checkout 1.7.4 release. This issue must be fixed there.
