### ISSUE TITLE
Version 1.7.6 fails installation on CI

### ISSUE THREAD

**Issue by ipanasenko** [evilmartians/lefthook#783]
### :wrench: Summary

Version 1.7.6 fails installation on CI, 1.7.5. works fine.
I have no issues with 1.7.6 locally on my mac.

We are using yarn 4.3.1.

### Lefthook version

`1.7.6 efa67f51e6a2d933dc539b2b1364eaade58351b5`

### Steps to reproduce

🤷‍♂️  Install in on Linux, I guess? 

### Expected results

Successful installation

### Actual results

Installation fails

### Possible Solution

🤷‍♂️ 

### Logs / Screenshots

Error I see in our logs:
```
STDERR /home/builduser/work/61a1e8a640f7a0a3/node_modules/lefthook-linux-x64/bin/lefthook: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/builduser/work/61a1e8a640f7a0a3/node_modules/lefthook-linux-x64/bin/lefthook)
```

**Comment by mrexox** [comment]
That's bad. I've checked the artifacts and they must not use shared libs. I will try to figure it out. Thank you for submitting an issue.

**Comment by ipanasenko** [comment]
`1.7.9` works for me, thanks!
