### ISSUE TITLE
Failure to execute script hooks when path to repository contains whitespace

### ISSUE THREAD

**Issue by bradchoate** [evilmartians/lefthook#819]
### :wrench: Summary

Similar issue to #403. A project directory containing a space causes issues.

### Lefthook version

1.7.15 5ad128101843299f0d9682616978d5d718cc534b

### Steps to reproduce

1. `$ mkdir "my project"`
2. `$ cd "my project"`
3. `$ git init`
4. `$ npm install @evilmartians/lefthook`
5. `$ npx lefthook install`
6. `$ echo "# hello" > readme.md`
7. `$ git add readme.md`
8. Create a `lefthook.yml` file that declares:
```yaml
prepare-commit-msg:
    scripts:
        "my-script.sh":
            runner: bash
```
9. Create a `.lefthook/prepare-commit-msg/my-script.sh` (and chmod +x):
```bash
#!/bin/bash
echo "prepare-commit-msg script ran"
```
10. `$ git commit`

### Expected results

Commit loads editor and on completion, prepare-commit-msg hook echoes "prepare-commit-msg script ran".

### Actual results

Git commit command fails as the prepare-commit-msg hook fails to execute, with the message:

```
|  my-script.sh >

bash: /path/to/my: No such file or directory
```

### Possible Solution

The script to execute via the runner should be quoted.

**Comment by mrexox** [comment]
Hey! Thank you for creating this issue. What's your OS? Is it Windows?

**Comment by bradchoate** [comment]
Sorry-- should have included that: macOS (Sonoma).

**Comment by bradchoate** [comment]
Can confirm this fixes the issue. Thanks for the quick update / release!
