### ISSUE TITLE
Add lefthook-bin to Arch install docs

### ISSUE THREAD

**Issue by ellsclytn** [evilmartians/lefthook#906]
### :zap: Summary

The [Arch Linux installation docs](https://github.com/evilmartians/lefthook/blob/f8bc2c309248621a53f71a2e19650742fe7ccc20/docs/install.md#-aur-for-arch) currently mention the [`lefthook` AUR package](https://aur.archlinux.org/packages/lefthook), but do not currently make note of the [`lefthook-bin` package](https://aur.archlinux.org/packages/lefthook-bin).

### Value

This may be preferable by many people who prefer to use precompiled binaries over having to have the application compiled locally.

I know this isn't really a "feature request" in the traditional sense, but that felt like the most suitable issue type. I'd happily open a PR, but I wanted to raise it as an issue first in case there may have been an active preference to only list the one package.

**Comment by mrexox** [comment]
Wow, I never saw this repo before! Thank you for mentioning! It makes sense to add this to docs.

BWT, currently I'm on a way of replacing these docs with the [new one](https://evilmartians.github.io/lefthook/) for convenience. But I'll add mentions to both.
